In [2]:
import random 
import pandas as pd
from haversine import haversine, Unit
import numpy as np

In [3]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [4]:
from scripts.PHMM.viterbi_algorithm.states import *
from scripts.PHMM.viterbi_algorithm.viterbi import *
from scripts.PHMM.distributions.AIS_RF_distribution import *
import pandas as pd

In [7]:
begin = BeginState()
AIS = AISState()
RF = RFState()
M = MState()
end = EndState()

states = [begin, AIS, RF, M, end]
model = PHMM(states, end)

In [8]:
test_set = pd.read_parquet("../data/processed/PHMM_sequence_data.parquet")
test_set

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
0,0,209112000,0,2024-01-03 13:19:57,NaT,NaT,None,None,begin
1,0,209112000,0,2024-01-03 13:19:58,2024-01-03 13:19:58,NaT,"[48.51548, -126.51201]",None,AIS
2,0,209112000,0,2024-01-03 13:32:50,2024-01-03 13:32:50,NaT,"[48.51033, -126.45776]",None,AIS
3,0,209112000,0,2024-01-03 13:34:50,2024-01-03 13:34:50,NaT,"[48.50968, -126.44914]",None,AIS
4,0,209112000,0,2024-01-03 13:40:59,2024-01-03 13:40:59,2024-01-03 13:41:00,"[48.50753, -126.42323]","[48.499443942360536, -126.4146031322306]",M
...,...,...,...,...,...,...,...,...,...
471750,710,677059800,0,2024-01-08 08:30:39,2024-01-08 08:30:39,NaT,"[19.00953, -68.1877]",None,AIS
471751,710,677059800,0,2024-01-08 08:47:23,2024-01-08 08:47:23,NaT,"[19.02076, -68.22079]",None,AIS
471752,710,677059800,0,2024-01-08 08:50:39,2024-01-08 08:50:39,NaT,"[19.02278, -68.22751]",None,AIS
471753,710,677059800,0,2024-01-08 09:41:00,NaT,2024-01-08 09:41:00,None,"[19.024754315587664, -68.23688644056789]",RF
471754,710,677059800,0,2024-01-08 09:41:01,NaT,NaT,None,None,end

In [9]:
sequence = test_set[test_set['TrackID'] == 5]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

RF_sequence = [(time, coord) for time, coord in zip(sequence["RF_Timestamp"], sequence["RF"]) 
               if pd.notna(time) and coord is not None][1:2]

In [10]:
RF_sequence

[(Timestamp('2024-01-03 09:41:00'), array([ 36.91790966, -75.90767514]))]

In [11]:
path, probability, log_probs = model.viterbi(AIS_sequence, RF_sequence)

[RESET] gap_counter = 0
0
0
2
4
4
4
6
8
10
10
10
12
14
16
16
16
18
20
22
22
22
24
26
28
28
28
30
32
34
34
34
36
38
40
40
40
42
44
46
46
46
48
50
52
52
52
54
56
58
58
58
60
62
64
64
64
66
68
70
70
70
72
74
76
76
76
78
80
82
82
82
84
86
88
88
88
90
92
94
94
94
96
98
100
100
100
102
104
106
106
106
108
110
112
112
112
114
116
118
118
118
120
122
124
124
124
126
128
130
130
130
132
134
136
136
136
138
140
142
142
142
144
146
148
148
148
150
152
154
154
154
156
158
160
160
160
162
164
166
166
166
168
170
172
172
172
174
176
178
178
178
180
182
184
184
184
186
188
190
190
190
192
194
196
196
196
198
200
202
202
202
204
206
208
208
208
210
212
214
214
214
216
218
220
220
220
222
224
226
226
226
228
230
232
232
232
234
236
238
238
238
240
242
244
244
244
246
248
250
250
250
252
254
256
256
256
258
260
262
262
262
264
266
268
268
268
270
272
274
274
274
276
278
280
280
280
282
284
286
286
286
288
290
292
292
292
294
296
298
298
298
300
302
304
304
304
306
308
310
310
310
312
314
316
316
316
318
320
322
322
322
324
326
328
328
328
330
332
334
334
334
336
338
340
340
340
342
344
346
346
346
348
350
352
352
352
354
356
358
358
358
360
362
364
364
364
366
368
370
370
370
372
374
376
376
376
378
380
382
382
382
384
386
388
388
388
390
392
394
394
394
396
398
400
400
400
402
404
406
406
406
408
410
412
412
412
414
416
418
418
418
420
422
424
424
424
426
428
430
430
430
432
434
436
436
436
438
440
442
442
442
444
446
448
448
448
450
452
454
454
454
456
458
460
460
460
462
464
466
466
466
468
470
472
472
472
474
476
478
478
478
480
482
484
484
484
486
488
490
490
490
492
494
496
496
496
498
500
502
502
502
504
506
508
508
508
510
512
514
514
514
516
518
520
520
520
522
524
526
526
526
528
530
532
532
532
534
536
538
538
538
540
542
544
544
544
546
548
550
550
550
552
554
556
556
556
558
560
562
562
562
564
566
568
568
568
570
572
574
574
574
576
578
580
580
580
582
584
586
586
586
588
590
592
592
592
594
596
598
598
598
600
602
604
604
604
606
608
610
610
610
612
614
616
616
616
618
620
622
622
622
624
626
628
628
631
637
637
642
644
644
644
646
648
650
650
650
652
654
656
656
656
658
660
662
662
662
664
666
668
668
668
670
672
674
674
674
676
678
680
680
680
682
684
686
686
686
688
690
692
692
692
694
696
698
698
698
700
702
704
704
704
706
708
710
710
710
712
714
716
716
716
718
720
722
722
722
724
726
728
728
728
730
732
734
734
734
736
738
740
740
740
742
744
746
746
746
748
750
752
752
752
754
756
758
758
758
760
762
764
764
764
766
768
770
770
770
772
774
776
776
776
778
780
782
782
782
784
786
788
788
788
790
792
794
794
794
796
798
800
800
800
802
804
806
806
806
808
810
812
812
812
814
816
818
818
818
820
822
824
824
824
826
828
830
830
830
832
834
836
836
836
837
837
839
840
840
840
840
840
840
840
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
841
842
843
843
843
844
848
848
850
851
851
852
854
854
855
855
856
856
857
859
859
860
860
861
861
862
864
864
865
865
866
866
867
869
869
870
870
871
871
872
874
874
875
875
876
876
877
879
879
880
880
881
881
882
884
884
885
885
886
886
887
889
889
890
890
891
891
892
894
894
895
895
896
896
897
899
899
900
900
901
901
902
904
904
905
905
906
906
907
909
909
910
910
911
911
912
914
914
915
915
916
916
917
919
919
920
920
921
921
922
924
924
925
925
926
926
927
929
929
930
930
931
931
932
934
934
935
935
936
936
937
939
939
940
940
941
941
942
944
944
945
945
946
946
947
949
949
950
950
951
951
952
954
954
955
955
956
956
957
959
959
960
960
961
961
962
964
964
965
965
966
966
967
969
969
970
970
971
971
972
974
974
975
975
976
976
977
979
979
980
980
981
981
982
984
984
985
985
986
986
987
989
989
990
990
991
991
992
994
994
995
995
996
996
997
999
999
1000
1000
1001
1001
1002
1004
1004
1005
1005
1006
1006
1007
1009
1009
1010
1010
1011
1011
1012
1014
1014
1015
1015
1016
1016
1017
1019
1019
1020
1020
1021
1021
1022
1024
1024
1025
1025
1026
1026
1027
1029
1029
1030
1030
1031
1031
1032
1034
1034
1035
1035
1036
1036
1037
1039
1039
1040
1040
1041
1041
1042
1044
1044
1045
1045
1046
1046
1047
1049
1049
1050
1050
1051
1051
1052
1054
1054
1055
1055
1056
1056
1057
1059
1059
1060
1060
1061
1061
1062
1064
1064
1065
1065
1066
1066
1067
1069
1069
1070
1070
1071
1071
1072
1074
1074
1075
1075
1076
1076
1077
1079
1079
1080
1080
1081
1081
1082
1084
1084
1085
1085
1086
1086
1087
1089
1089
1090
1090
1091
1091
1092
1094
1094
1095
1095
1096
1096
1097
1099
1099
1100
1100
1101
1101
1102
1104
1104
1105
1105
1106
1106
1107
1109
1109
1110
1110
1111
1111
1112
1114
1114
1115
1115
1116
1116
1117
1119
1119
1120
1120
1121
1121
1122
1124
1124
1125
1125
1126
1126
1127
1129
1129
1130
1130
1131
1131
1132
1134
1134
1135
1135
1136
1136
1137
1139
1139
1140
1140
1141
1141
1142
1144
1144
1145
1145
1146
1146
1147
1149
1149
1150
1150
1151
1151
1152
1154
1154
1155
1155
1156
1156
1157
1159
1159
1160
1160
1161
1161
1162
1164
1164
1165
1165
1166
1166
1167
1169
1169
1170
1170
1171
1171
1172
1174
1174
1175
1175
1176
1176
1177
1179
1179
1180
1180
1181
1181
1182
1184
1184
1185
1185
1186
1186
1187
1189
1189
1190
1190
1191
1191
1192
1194
1194
1195
1195
1196
1196
1197
1199
1199
1200
1200
1201
1201
1202
1204
1204
1205
1205
1206
1206
1207
1209
1209
1210
1210
1211
1211
1212
1214
1214
1215
1215
1216
1216
1217
1219
1219
1220
1220
1221
1221
1222
1224
1224
1225
1225
1226
1226
1227
1229
1229
1230
1230
1231
1231
1232
1234
1234
1235
1235
1236
1236
1237
1239
1239
1240
1240
1241
1241
1242
1244
1244
1245
1245
1246
1246
1247
1249
1249
1250
1250
1251
1251
1252
1254
1254
1255
1255
1256
1256
1257
1259
1259
1260
1260
1261
1261
1262
1264
1264
1265
1265
1266
1266
1267
1269
1269
1270
1270
1271
1271
1272
1274
1274
1275
1275
1276
1276
1277
1279
1279
1280
1280
1281
1281
1282
1284
1284
1285
1285
1286
1286
1287
1289
1289
1290
1290
1291
1291
1292
1294
1294
1295
1295
1296
1296
1297
1299
1299
1300
1300
1301
1301
1302
1304
1304
1305
1305
1306
1306
1307
1309
1309
1310
1310
1311
1311
1312
1314
1314
1315
1315
1316
1316
1317
1319
1319
1320
1320
1321
1321
1322
1324
1324
1325
1325
1326
1326
1327
1329
1329
1330
1330
1331
1331
1332
1334
1334
1335
1335
1336
1336
1337
1339
1339
1340
1340
1341
1341
1342
1344
1344
1345
1345
1346
1346
1347
1349
1349
1350
1350
1351
1351
1352
1354
1354
1355
1355
1356
1356
1357
1359
1359
1360
1360
1361
1361
1362
1364
1364
1365
1365
1366
1366
1367
1369
1369
1370
1370
1371
1371
1372
1374
1374
1375
1375
1376
1376
1377
1379
1379
1380
1380
1381
1381
1382
1384
1384
1385
1385
1386
1386
1387
1389
1389
1390
1390
1391
1391
1392
1394
1394
1395
1395
1396
1396
1397
1399
1399
1400
1400
1401
1401
1402
1404
1404
1405
1405
1406
1406
1407
1409
1409
1410
1410
1411
1411
1412
1414
1414
1415
1415
1416
1416
1417
1419
1419
1420
1420
1421
1421
1422
1424
1424
1425
1425
1426
1426
1427
1429
1429
1430
1430
1431
1431
1432
1434
1434
1435
1435
1436
1436
1437
1439
1439
1440
1440
1441
1441
1442
1444
1444
1445
1445
1446
1446
1447
1449
1449
1450
1450
1451
1451
1452
1454
1454
1455
1455
1456
1456
1457
1459
1459
1460
1460
1461
1461
1462
1464
1464
1465
1465
1466
1466
1467
1469
1469
1470
1470
1471
1471
1472
1474
1474
1475
1475
1476
1476
1477
1479
1479
1480
1480
1481
1481
1482
1484
1484
1485
1485
1486
1486
1487
1489
1489
1490
1490
1491
1491
1492
1494
1494
1495
1495
1496
1496
1497
1499
1499
1500
1500
1501
1501
1502
1504
1504
1505
1505
1506
1506
1507
1509
1509
1510
1510
1511
1511
1512
1514
1514
1515
1515
1516
1516
1517
1519
1519
1520
1520
1521
1521
1522
1524
1524
1525
1525
1526
1526
1527
1529
1529
1530
1530
1531
1531
1532
1534
1534
1535
1535
1536
1536
1537
1539
1539
1540
1540
1541
1541
1542
1544
1544
1545
1545
1546
1546
1547
1549
1549
1550
1550
1551
1551
1552
1554
1554
1555
1555
1556
1556
1557
1559
1559
1560
1560
1561
1561
1562
1564
1564
1565
1565
1566
1566
1567
1569
1569
1570
1570
1571
1571
1572
1574
1574
1575
1575
1576
1576
1577
1580
1581
1581
1583
1587
1587
1589
1590
1590
1591
1593
1593
1594
1594
1595
1595
1596
1598
1598
1599
1599
1600
1600
1601
1603
1603
1604
1604
1605
1605
1606
1608
1608
1609
1609
1610
1610
1611
1613
1613
1614
1614
1615
1615
1616
1618
1618
1619
1619
1620
1620
1621
1623
1623
1624
1624
1625
1625
1626
1628
1628
1629
1629
1630
1630
1631
1633
1633
1634
1634
1635
1635
1636
1638
1638
1639
1639
1640
1640
1641
1643
1643
1644
1644
1645
1645
1646
1648
1648
1649
1649
1650
1650
1651
1653
1653
1654
1654
1655
1655
1656
1658
1658
1659
1659
1660
1660
1661
1663
1663
1664
1664
1665
1665
1666
1668
1668
1669
1669
1670
1670
1671
1673
1673
1674
1674
1675
1675
1676
1678
1678
1679
1679
1680
1680
1681
1683
1683
1684
1684
1685
1685
1686
1688
1688
1689
1689
1690
1690
1691
1693
1693
1694
1694
1695
1695
1696
1698
1698
1699
1699
1700
1700
1701
1703
1703
1704
1704
1705
1705
1706
1708
1708
1709
1709
1710
1710
1711
1713
1713
1714
1714
1715
1715
1716
1718
1718
1719
1719
1720
1720
1721
1723
1723
1724
1724
1725
1725
1726
1728
1728
1729
1729
1730
1730
1731
1733
1733
1734
1734
1735
1735
1736
1738
1738
1739
1739
1740
1740
1741
1743
1743
1744
1744
1745
1745
1746
1748
1748
1749
1749
1750
1750
1751
1753
1753
1754
1754
1755
1755
1756
1758
1758
1759
1759
1760
1760
1761
1763
1763
1764
1764
1765
1765
1766
1768
1768
1769
1769
1770
1770
1771
1773
1773
1774
1774
1775
1775
1776
1778
1778
1779
1779
1780
1780
1781
1783
1783
1784
1784
1785
1785
1786
1788
1788
1789
1789
1790
1790
1791
1793
1793
1794
1794
1795
1795
1796
1798
1798
1799
1799
1800
1800
1801
1803
1803
1804
1804
1805
1805
1806
1808
1808
1809
1809
1810
1810
1811
1813
1813
1814
1814
1815
1815
1816
1818
1818
1819
1819
1820
1820
1821
1823
1823
1824
1824
1825
1825
1826
1828
1828
1829
1829
1830
1830
1831
1833
1833
1834
1834
1835
1835
1836
1838
1838
1839
1839
1840
1840
1841
1843
1843
1844
1844
1845
1845
1846
1848
1848
1849
1849
1850
1850
1851
1853
1853
1854
1854
1855
1855
1856
1858
1858
1859
1859
1860
1860
1861
1863
1863
1864
1864
1865
1865
1866
1868
1868
1869
1869
1870
1870
1871
1873
1873
1874
1874
1875
1875
1876
1878
1878
1879
1879
1880
1880
1881
1883
1883
1884
1884
1885
1885
1886
1888
1888
1889
1889
1890
1890
1891
1893
1893
1894
1894
1895
1895
1896
1898
1898
1899
1899
1900
1900
1901
1903
1903
1904
1904
1905
1905
1906
1908
1908
1909
1909
1910
1910
1911
1913
1913
1914
1914
1915
1915
1916
1918
1918
1919
1919
1920
1920
1921
1923
1923
1924
1924
1925
1925
1926
1928
1928
1929
1929
1930
1930
1931
1933
1933
1934
1934
1935
1935
1936
1938
1938
1939
1939
1940
1940
1941
1943
1943
1944
1944
1945
1945
1946
1948
1948
1949
1949
1950
1950
1951
1953
1953
1954
1954
1955
1955
1956
1958
1958
1959
1959
1960
1960
1961
1963
1963
1964
1964
1965
1965
1966
1968
1968
1969
1969
1970
1970
1971
1973
1973
1974
1974
1975
1975
1976
1978
1978
1979
1979
1980
1980
1981
1983
1983
1984
1984
1985
1985
1986
1988
1988
1989
1989
1990
1990
1991
1993
1993
1994
1994
1995
1995
1996
1998
1998
1999
1999
2000
2000
2001
2003
2003
2004
2004
2005
2005
2006
2008
2008
2009
2009
2010
2010
2011
2013
2013
2014
2014
2015
2015
2016
2018
2018
2019
2019
2020
2020
2021
2023
2023
2024
2024
2025
2025
2026
2028
2028
2029
2029
2030
2030
2031
2033
2033
2034
2034
2035
2035
2036
2038
2038
2039
2039
2040
2040
2041
2043
2043
2044
2044
2045
2045
2046
2048
2048
2049
2049
2050
2050
2051
2053
2053
2054
2054
2055
2055
2056
2058
2058
2059
2059
2060
2060
2061
2063
2063
2064
2064
2065
2065
2066
2068
2068
2069
2069
2070
2070
2071
2073
2073
2074
2074
2075
2075
2076
2078
2078
2078

In [12]:
RF_M_indexes_pred_path = [(i, state) for i, state in enumerate(path) if state in {"RF", "M"}]
RF_M_indexes_real_path = [(i, state) for i, state in enumerate(sequence["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path}")

The indexes of RF and/or M of predicted path are: [(219, 'RF')],
The indexes of RF and/or M of the real path are: [(34, 'RF'), (220, 'M'), (350, 'M'), (544, 'RF')]

In [13]:
print(probability)
print(probability/len(path))

-27.615797928507973
-0.05067118885964766

In [17]:
df = test_set[test_set["TrackID"] == 5].copy()
match_rows = df[df["State"] == "M"]

ais_rows = match_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

rf_from_match = match_rows.copy()
rf_from_match["AIS"] = None
rf_from_match["AIS_Timestamp"] = pd.NaT
rf_from_match["Timestamp"] = rf_from_match["RF_Timestamp"]
rf_from_match["State"] = "RF"

rf_from_original = df[df["State"] == "RF"]
all_rf_candidates = pd.concat([rf_from_original, rf_from_match], ignore_index=True)
chosen_rf = all_rf_candidates.sort_values(by="RF_Timestamp")[1:2]

df = df[(df["State"] != "M") & (df["State"] != "RF")]
df = pd.concat([df, ais_rows, chosen_rf], ignore_index=True)
df = df.sort_values(by="Timestamp").reset_index(drop=True)

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged = df.copy().reset_index(drop=True)
df_merged["BestPathState"] = df_path["State"]
df_merged["LogProb"] = df_path["LogProb"]
df_merged["Probability"] = np.exp(df_path["LogProb"])

df_merged["prev_Timestamp"] = df_merged["Timestamp"].shift(1)
df_merged["delta_time_sec"] = (df_merged["Timestamp"] - df_merged["prev_Timestamp"]).dt.total_seconds()

df_merged["coord"] = df_merged["AIS"].combine_first(df_merged["RF"])
df_merged["prev_coord"] = df_merged["coord"].shift(1)
df_merged["distance_km"] = None  

for idx, row in df_merged.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged.at[idx, "distance_km"] = dist
        
df_merged["prev_state"] = df_merged["State"].shift(1)
df_merged["transition"] = df_merged["prev_state"] + "→" + df_merged["State"]
df_merged["trans_prob"] = np.nan

for idx, row in df_merged.iterrows():
    trans = row["transition"]

    if row["prev_state"] == "begin":
        trans_prob = 0.3

    elif trans in ["AIS→AIS", "AIS→RF", "RF→RF", "RF→AIS"]:
        prev = df_merged.loc[idx - 1]

        if trans == "AIS→AIS":
            time = (row["AIS_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "AIS→RF":
            time = (row["RF_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→RF":
            time = (row["RF_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→AIS":
            time = (row["AIS_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)

    elif row["State"] == "end":
        trans_prob = 0.05
    
    else:
        continue

    df_merged.at[idx, "trans_prob"] = trans_prob

df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
0,5,210614000,2,2024-01-03 00:03:02,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN
1,5,210614000,2,2024-01-03 00:03:03,2024-01-03 00:03:03,NaT,"[36.96283, -76.42414]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:03:02,1.0,"[36.96283, -76.42414]",None,None,begin,begin→AIS,0.300000
2,5,210614000,2,2024-01-03 00:06:03,2024-01-03 00:06:03,NaT,"[36.96283, -76.42412]",None,AIS,AIS,-1.127221,3.239323e-01,2024-01-03 00:03:03,180.0,"[36.96283, -76.42412]","[36.96283, -76.42414]",0.001777,AIS,AIS→AIS,0.981828
3,5,210614000,2,2024-01-03 00:09:03,2024-01-03 00:09:03,NaT,"[36.96282, -76.42411]",None,AIS,AIS,-1.153941,3.153913e-01,2024-01-03 00:06:03,180.0,"[36.96282, -76.42411]","[36.96283, -76.42412]",0.001423,AIS,AIS→AIS,0.981880
4,5,210614000,2,2024-01-03 00:12:03,2024-01-03 00:12:03,NaT,"[36.96282, -76.42409]",None,AIS,AIS,-1.180245,3.072034e-01,2024-01-03 00:09:03,180.0,"[36.96282, -76.42409]","[36.96282, -76.42411]",0.001777,AIS,AIS→AIS,0.981828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,5,210614000,2,2024-01-03 20:35:06,2024-01-03 20:35:06,NaT,"[36.04509, -73.8082]",None,AIS,AIS,-24.543126,2.193087e-11,2024-01-03 20:12:17,1369.0,"[36.04509, -73.8082]","[36.0808, -73.89056]",8.400754,AIS,AIS→AIS,0.247199
541,5,210614000,2,2024-01-03 20:39:06,2024-01-03 20:39:06,NaT,"[36.03897, -73.79441]",None,AIS,AIS,-24.568772,2.137557e-11,2024-01-03 20:35:06,240.0,"[36.03897, -73.79441]","[36.04509, -73.8082]",1.414346,AIS,AIS→AIS,0.789585
542,5,210614000,2,2024-01-03 20:44:27,2024-01-03 20:44:27,NaT,"[36.03039, -73.77547]",None,AIS,AIS,-24.594419,2.083433e-11,2024-01-03 20:39:06,321.0,"[36.03039, -73.77547]","[36.03897, -73.79441]",1.952091,AIS,AIS→AIS,0.722497
543,5,210614000,2,2024-01-03 21:07:57,2024-01-03 21:07:57,NaT,"[35.99436, -73.69102]",None,AIS,AIS,-24.620066,2.030679e-11,2024-01-03 20:44:27,1410.0,"[35.99436, -73.69102]","[36.03039, -73.77547]",8.58763,AIS,AIS→AIS,0.239378
544,5,210614000,2,2024-01-03 21:41:01,NaT,NaT,None,None,end,end,-27.615798,1.015340e-12,2024-01-03 21:07:57,1984.0,None,"[35.99436, -73.69102]",None,AIS,AIS→end,0.050000

In [19]:
df_merged.sort_values(by=["delta_time_sec"], ascending=False)

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
107,5,210614000,2,2024-01-03 07:32:37,2024-01-03 07:32:37,NaT,"[36.98653, -76.31608]",None,AIS,AIS,-4.376353,1.257112e-02,2024-01-03 05:18:03,8074.0,"[36.98653, -76.31608]","[36.96283, -76.42408]",9.949419,AIS,AIS→AIS,0.010000
445,5,210614000,2,2024-01-03 17:02:27,2024-01-03 17:02:27,NaT,"[36.34553, -74.54543]",None,AIS,AIS,-22.106694,2.507175e-10,2024-01-03 15:30:57,5490.0,"[36.34553, -74.54543]","[36.47445, -74.84854]",30.679964,AIS,AIS→AIS,0.010000
298,5,210614000,2,2024-01-03 12:40:47,2024-01-03 12:40:47,NaT,"[36.69973, -75.38304]",None,AIS,AIS,-18.336637,1.087676e-08,2024-01-03 11:10:36,5411.0,"[36.69973, -75.38304]","[36.77195, -75.6805]",27.69696,AIS,AIS→AIS,0.010000
544,5,210614000,2,2024-01-03 21:41:01,NaT,NaT,None,None,end,end,-27.615798,1.015340e-12,2024-01-03 21:07:57,1984.0,None,"[35.99436, -73.69102]",None,AIS,AIS→end,0.050000
543,5,210614000,2,2024-01-03 21:07:57,2024-01-03 21:07:57,NaT,"[35.99436, -73.69102]",None,AIS,AIS,-24.620066,2.030679e-11,2024-01-03 20:44:27,1410.0,"[35.99436, -73.69102]","[36.03039, -73.77547]",8.58763,AIS,AIS→AIS,0.239378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,5,210614000,2,2024-01-03 09:41:00,NaT,2024-01-03 09:41:00,None,"[36.917909658337884, -75.90767513607126]",RF,RF,-16.310552,8.249304e-08,2024-01-03 09:40:27,33.0,"[36.917909658337884, -75.90767513607126]","[36.91522, -75.91979]",1.117786,AIS,AIS→RF,0.842838
183,5,210614000,2,2024-01-03 09:00:07,2024-01-03 09:00:07,NaT,"[36.95467, -76.0385]",None,AIS,AIS,-7.301911,6.742494e-04,2024-01-03 08:59:36,31.0,"[36.95467, -76.0385]","[36.95503, -76.04017]",0.153696,AIS,AIS→AIS,0.974173
237,5,210614000,2,2024-01-03 10:00:07,2024-01-03 10:00:07,NaT,"[36.87622, -75.87551]",None,AIS,AIS,-16.772192,5.199119e-08,2024-01-03 09:59:57,10.0,"[36.87622, -75.87551]","[36.87652, -75.87591]",0.048772,AIS,AIS→AIS,0.991715
1,5,210614000,2,2024-01-03 00:03:03,2024-01-03 00:03:03,NaT,"[36.96283, -76.42414]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:03:02,1.0,"[36.96283, -76.42414]",None,None,begin,begin→AIS,0.300000
0,5,210614000,2,2024-01-03 00:03:02,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN

In [15]:
df_merged[df_merged["transition"] == "AIS→RF"]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
219,5,210614000,2,2024-01-03 09:41:00,NaT,2024-01-03 09:41:00,None,"[36.917909658337884, -75.90767513607126]",RF,RF,-16.310552,8.249304e-08,2024-01-03 09:40:27,33.0,"[36.917909658337884, -75.90767513607126]","[36.91522, -75.91979]",1.117786,AIS,AIS→RF,0.842838

In [16]:
df_merged.sort_values(by=["trans_prob"], inplace=True)
df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
445,5,210614000,2,2024-01-03 17:02:27,2024-01-03 17:02:27,NaT,"[36.34553, -74.54543]",None,AIS,AIS,-22.106694,2.507175e-10,2024-01-03 15:30:57,5490.0,"[36.34553, -74.54543]","[36.47445, -74.84854]",30.679964,AIS,AIS→AIS,0.010000
298,5,210614000,2,2024-01-03 12:40:47,2024-01-03 12:40:47,NaT,"[36.69973, -75.38304]",None,AIS,AIS,-18.336637,1.087676e-08,2024-01-03 11:10:36,5411.0,"[36.69973, -75.38304]","[36.77195, -75.6805]",27.69696,AIS,AIS→AIS,0.010000
107,5,210614000,2,2024-01-03 07:32:37,2024-01-03 07:32:37,NaT,"[36.98653, -76.31608]",None,AIS,AIS,-4.376353,1.257112e-02,2024-01-03 05:18:03,8074.0,"[36.98653, -76.31608]","[36.96283, -76.42408]",9.949419,AIS,AIS→AIS,0.010000
544,5,210614000,2,2024-01-03 21:41:01,NaT,NaT,None,None,end,end,-27.615798,1.015340e-12,2024-01-03 21:07:57,1984.0,None,"[35.99436, -73.69102]",None,AIS,AIS→end,0.050000
543,5,210614000,2,2024-01-03 21:07:57,2024-01-03 21:07:57,NaT,"[35.99436, -73.69102]",None,AIS,AIS,-24.620066,2.030679e-11,2024-01-03 20:44:27,1410.0,"[35.99436, -73.69102]","[36.03039, -73.77547]",8.58763,AIS,AIS→AIS,0.239378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,5,210614000,2,2024-01-03 04:33:03,2024-01-03 04:33:03,NaT,"[36.96278, -76.42407]",None,AIS,AIS,-3.417226,3.280330e-02,2024-01-03 04:30:03,180.0,"[36.96278, -76.42407]","[36.96278, -76.42407]",0.0,AIS,AIS→AIS,0.982090
72,5,210614000,2,2024-01-03 03:36:03,2024-01-03 03:36:03,NaT,"[36.96278, -76.42409]",None,AIS,AIS,-2.929538,5.342173e-02,2024-01-03 03:33:03,180.0,"[36.96278, -76.42409]","[36.96278, -76.42409]",0.0,AIS,AIS→AIS,0.982090
78,5,210614000,2,2024-01-03 03:54:03,2024-01-03 03:54:03,NaT,"[36.96278, -76.42409]",None,AIS,AIS,-3.083555,4.579615e-02,2024-01-03 03:51:03,180.0,"[36.96278, -76.42409]","[36.96278, -76.42409]",0.0,AIS,AIS→AIS,0.982090
237,5,210614000,2,2024-01-03 10:00:07,2024-01-03 10:00:07,NaT,"[36.87622, -75.87551]",None,AIS,AIS,-16.772192,5.199119e-08,2024-01-03 09:59:57,10.0,"[36.87622, -75.87551]","[36.87652, -75.87591]",0.048772,AIS,AIS→AIS,0.991715
0,5,210614000,2,2024-01-03 00:03:02,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN

In [17]:
sequence = test_set[test_set['TrackID'] == 79]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

In [18]:
path, probability, log_probs = model.viterbi(AIS_sequence, RF_sequence)

In [19]:
print(probability)
print(probability/len(path))

-34.59862879259538
-0.052263789716911445

In [18]:
RF_M_indexes_pred_path = [(i, state) for i, state in enumerate(path) if state in {"RF", "M"}]
RF_M_indexes_real_path = [(i, state) for i, state in enumerate(sequence["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path}")

The indexes of RF and/or M of predicted path are: [(378, 'RF')],
The indexes of RF and/or M of the real path are: [(1, 'RF'), (505, 'M')]

In [19]:
df_rf = test_set[test_set["TrackID"] == 5].copy()
match_rf_rows = df_rf[df_rf["State"] == "M"]

rf_from_match = match_rf_rows.copy()
rf_from_match["AIS"] = None
rf_from_match["AIS_Timestamp"] = pd.NaT
rf_from_match["Timestamp"] = rf_from_match["RF_Timestamp"]
rf_from_match["State"] = "RF"

rf_from_original = df_rf[df_rf["State"] == "RF"]
all_rf_candidates = pd.concat([rf_from_original, rf_from_match], ignore_index=True)
chosen_rf = all_rf_candidates.sort_values(by="RF_Timestamp").iloc[1:2]

df_ais = test_set[test_set["TrackID"] == 79].copy()
match_ais_rows = df_ais[df_ais["State"] == "M"]

ais_rows = match_ais_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

df = df_ais[(df_ais["State"] != "M") & (df_ais["State"] != "RF")]
combined_df = pd.concat([df, ais_rows, chosen_rf], ignore_index=True)
combined_df = combined_df.sort_values(by="Timestamp").reset_index(drop=True)

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged2 = combined_df.copy().reset_index(drop=True)
df_merged2["BestPathState"] = df_path["State"]
df_merged2["LogProb"] = df_path["LogProb"]
df_merged2["Probability"] = np.exp(df_path["LogProb"])

df_merged2["prev_Timestamp"] = df_merged2["Timestamp"].shift(1)
df_merged2["delta_time_sec"] = (df_merged2["Timestamp"] - df_merged2["prev_Timestamp"]).dt.total_seconds()

df_merged2["coord"] = df_merged2["AIS"].combine_first(df_merged2["RF"])
df_merged2["prev_coord"] = df_merged2["coord"].shift(1)
df_merged2["distance_km"] = None  

for idx, row in df_merged2.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged2.at[idx, "distance_km"] = dist

df_merged2["prev_state"] = df_merged2["State"].shift(1)
df_merged2["transition"] = df_merged2["prev_state"] + "→" + df_merged2["State"]
df_merged2["trans_prob"] = np.nan

for idx, row in df_merged2.iterrows():
    trans = row["transition"]

    if row["prev_state"] == "begin":
        trans_prob = 0.3

    elif trans in ["AIS→AIS", "AIS→RF", "RF→RF", "RF→AIS"]:
        prev = df_merged2.loc[idx - 1]

        if trans == "AIS→AIS":
            time = (row["AIS_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "AIS→RF":
            time = (row["RF_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→RF":
            time = (row["RF_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→AIS":
            time = (row["AIS_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
                
    elif row["State"] == "end":
        trans_prob = 0.05
    
    else:
        continue

    df_merged2.at[idx, "trans_prob"] = trans_prob

df_merged2

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
0,79,247310400,2,2024-01-02 21:40:59,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN
1,79,247310400,2,2024-01-02 23:59:33,2024-01-02 23:59:33,NaT,"[39.1948, -76.48997]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-02 21:40:59,8314.0,"[39.1948, -76.48997]",None,None,begin,begin→AIS,0.300000
2,79,247310400,2,2024-01-03 00:00:03,2024-01-03 00:00:03,NaT,"[39.19433, -76.48838]",None,AIS,AIS,-1.134417,3.216096e-01,2024-01-02 23:59:33,30.0,"[39.19433, -76.48838]","[39.1948, -76.48997]",0.146649,AIS,AIS→AIS,0.974470
3,79,247310400,2,2024-01-03 00:02:53,2024-01-03 00:02:53,NaT,"[39.19167, -76.47924]",None,AIS,AIS,-1.171525,3.098941e-01,2024-01-03 00:00:03,170.0,"[39.19167, -76.47924]","[39.19433, -76.48838]",0.841376,AIS,AIS→AIS,0.862567
4,79,247310400,2,2024-01-03 00:04:04,2024-01-03 00:04:04,NaT,"[39.19053, -76.47539]",None,AIS,AIS,-1.207702,2.988835e-01,2024-01-03 00:02:53,71.0,"[39.19053, -76.47539]","[39.19167, -76.47924]",0.355187,AIS,AIS→AIS,0.939676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,79,247310400,2,2024-01-03 17:02:27,2024-01-03 17:02:27,NaT,"[35.57177, -74.40962]",None,AIS,AIS,-31.831891,1.498254e-14,2024-01-03 17:00:27,120.0,"[35.57177, -74.40962]","[35.57831, -74.41664]",0.965368,AIS,AIS→AIS,0.860027
658,79,247310400,2,2024-01-03 17:03:45,2024-01-03 17:03:45,NaT,"[35.56753, -74.40505]",None,AIS,AIS,-31.857537,1.460318e-14,2024-01-03 17:02:27,78.0,"[35.56753, -74.40505]","[35.57177, -74.40962]",0.627004,AIS,AIS→AIS,0.906691
659,79,247310400,2,2024-01-03 17:05:09,2024-01-03 17:05:09,NaT,"[35.56301, -74.40028]",None,AIS,AIS,-31.883184,1.423342e-14,2024-01-03 17:03:45,84.0,"[35.56301, -74.40028]","[35.56753, -74.40505]",0.662392,AIS,AIS→AIS,0.901330
660,79,247310400,2,2024-01-03 17:11:21,2024-01-03 17:11:21,NaT,"[35.54379, -74.37878]",None,AIS,AIS,-31.908830,1.387302e-14,2024-01-03 17:05:09,372.0,"[35.54379, -74.37878]","[35.56301, -74.40028]",2.889731,AIS,AIS→AIS,0.634708
661,79,247310400,2,2024-01-03 17:11:22,NaT,NaT,None,None,end,end,-34.904563,6.936510e-16,2024-01-03 17:11:21,1.0,None,"[35.54379, -74.37878]",None,AIS,AIS→end,0.050000

In [20]:
test_set[test_set["TrackID"] == 79]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
48252,79,247310400,2,2024-01-02 21:40:59,NaT,NaT,None,None,begin
48253,79,247310400,2,2024-01-02 21:41:00,NaT,2024-01-02 21:41:00,None,"[39.192009451935135, -76.4795149778899]",RF
48254,79,247310400,2,2024-01-02 23:59:33,2024-01-02 23:59:33,NaT,"[39.1948, -76.48997]",None,AIS
48255,79,247310400,2,2024-01-03 00:00:03,2024-01-03 00:00:03,NaT,"[39.19433, -76.48838]",None,AIS
48256,79,247310400,2,2024-01-03 00:02:53,2024-01-03 00:02:53,NaT,"[39.19167, -76.47924]",None,AIS
...,...,...,...,...,...,...,...,...,...
48909,79,247310400,2,2024-01-03 17:02:27,2024-01-03 17:02:27,NaT,"[35.57177, -74.40962]",None,AIS
48910,79,247310400,2,2024-01-03 17:03:45,2024-01-03 17:03:45,NaT,"[35.56753, -74.40505]",None,AIS
48911,79,247310400,2,2024-01-03 17:05:09,2024-01-03 17:05:09,NaT,"[35.56301, -74.40028]",None,AIS
48912,79,247310400,2,2024-01-03 17:11:21,2024-01-03 17:11:21,NaT,"[35.54379, -74.37878]",None,AIS
48913,79,247310400,2,2024-01-03 17:11:22,NaT,NaT,None,None,end

In [22]:
df_merged2[df_merged2["transition"] == "AIS→RF"]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
378,5,210614000,2,2024-01-03 09:41:00,NaT,2024-01-03 09:41:00,None,"[36.917909658337884, -75.90767513607126]",RF,RF,-24.676476,1.919299e-11,2024-01-03 09:40:22,38.0,"[36.917909658337884, -75.90767513607126]","[36.88085, -75.89407]",4.294766,AIS,AIS→RF,0.57904

In [21]:
df_merged2.sort_values(by=["trans_prob"], inplace=True)
df_merged2

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
436,79,247310400,2,2024-01-03 12:25:45,2024-01-03 12:25:45,NaT,"[36.44869, -75.37019]",None,AIS,AIS,-26.163982,4.336379e-12,2024-01-03 10:46:33,5952.0,"[36.44869, -75.37019]","[36.77036, -75.71237]",47.033926,AIS,AIS→AIS,0.010000
158,79,247310400,2,2024-01-03 05:36:10,2024-01-03 05:36:10,NaT,"[37.76549, -76.18694]",None,AIS,AIS,-7.351033,6.419287e-04,2024-01-03 02:56:45,9565.0,"[37.76549, -76.18694]","[38.50747, -76.40766]",84.732694,AIS,AIS→AIS,0.010000
661,79,247310400,2,2024-01-03 17:11:22,NaT,NaT,None,None,end,end,-34.904563,6.936510e-16,2024-01-03 17:11:21,1.0,None,"[35.54379, -74.37878]",None,AIS,AIS→end,0.050000
1,79,247310400,2,2024-01-02 23:59:33,2024-01-02 23:59:33,NaT,"[39.1948, -76.48997]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-02 21:40:59,8314.0,"[39.1948, -76.48997]",None,None,begin,begin→AIS,0.300000
637,79,247310400,2,2024-01-03 16:29:46,2024-01-03 16:29:46,NaT,"[35.68175, -74.51933]",None,AIS,AIS,-31.318958,2.502359e-14,2024-01-03 16:20:45,541.0,"[35.68175, -74.51933]","[35.71183, -74.54945]",4.311078,AIS,AIS→AIS,0.509320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,79,247310400,2,2024-01-03 13:00:04,2024-01-03 13:00:04,NaT,"[36.34853, -75.24576]",None,AIS,AIS,-26.984674,1.908556e-12,2024-01-03 12:59:39,25.0,"[36.34853, -75.24576]","[36.34978, -75.24725]",0.192682,AIS,AIS→AIS,0.970096
2,79,247310400,2,2024-01-03 00:00:03,2024-01-03 00:00:03,NaT,"[39.19433, -76.48838]",None,AIS,AIS,-1.134417,3.216096e-01,2024-01-02 23:59:33,30.0,"[39.19433, -76.48838]","[39.1948, -76.48997]",0.146649,AIS,AIS→AIS,0.974470
523,79,247310400,2,2024-01-03 14:00:04,2024-01-03 14:00:04,NaT,"[36.16839, -75.02775]",None,AIS,AIS,-28.395240,4.656976e-13,2024-01-03 13:59:45,19.0,"[36.16839, -75.02775]","[36.16933, -75.02895]",0.150095,AIS,AIS→AIS,0.976744
396,79,247310400,2,2024-01-03 10:00:04,2024-01-03 10:00:04,NaT,"[36.84757, -75.84144]",None,AIS,AIS,-25.138116,1.209637e-11,2024-01-03 09:59:53,11.0,"[36.84757, -75.84144]","[36.84784, -75.84198]",0.056658,AIS,AIS→AIS,0.990205
0,79,247310400,2,2024-01-02 21:40:59,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN

In [22]:
sequence = test_set[test_set['TrackID'] == 197]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

In [23]:
path, probability, log_probs = model.viterbi(AIS_sequence, RF_sequence)

In [24]:
print(probability)
print(probability/len(path))

-17.69218727503968
-0.05026189566772636

In [25]:
RF_M_indexes_pred_path = [(i, state) for i, state in enumerate(path) if state in {"RF", "M"}]
RF_M_indexes_real_path = [(i, state) for i, state in enumerate(sequence["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path}")

The indexes of RF and/or M of predicted path are: [(73, 'RF')],
The indexes of RF and/or M of the real path are: [(73, 'M'), (322, 'RF')]

In [ ]:
df_rf = test_set[test_set["TrackID"] == 46].copy()
match_rf_rows = df_rf[df_rf["State"] == "M"]

rf_from_match = match_rf_rows.copy()
rf_from_match["AIS"] = None
rf_from_match["AIS_Timestamp"] = pd.NaT
rf_from_match["Timestamp"] = rf_from_match["RF_Timestamp"]
rf_from_match["State"] = "RF"

rf_from_original = df_rf[df_rf["State"] == "RF"]
all_rf_candidates = pd.concat([rf_from_original, rf_from_match], ignore_index=True)
chosen_rf = all_rf_candidates.sort_values(by="RF_Timestamp").iloc[2:3]

df_ais = test_set[test_set["TrackID"] == 197].copy()
match_ais_rows = df_ais[df_ais["State"] == "M"]

ais_rows = match_ais_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

df = df_ais[(df_ais["State"] != "M") & (df_ais["State"] != "RF")]
combined_df = pd.concat([df, ais_rows, chosen_rf], ignore_index=True)
combined_df = combined_df.sort_values(by="Timestamp").reset_index(drop=True)

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged2 = combined_df.copy().reset_index(drop=True)
df_merged2["BestPathState"] = df_path["State"]
df_merged2["LogProb"] = df_path["LogProb"]
df_merged2["Probability"] = np.exp(df_path["LogProb"])

df_merged2["prev_Timestamp"] = df_merged2["Timestamp"].shift(1)
df_merged2["delta_time_sec"] = (df_merged2["Timestamp"] - df_merged2["prev_Timestamp"]).dt.total_seconds()

df_merged2["coord"] = df_merged2["AIS"].combine_first(df_merged2["RF"])
df_merged2["prev_coord"] = df_merged2["coord"].shift(1)
df_merged2["distance_km"] = None  

for idx, row in df_merged2.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged2.at[idx, "distance_km"] = dist

df_merged2["prev_state"] = df_merged2["State"].shift(1)
df_merged2["transition"] = df_merged2["prev_state"] + "→" + df_merged2["State"]
df_merged2["trans_prob"] = np.nan

gap_counter = 0

for idx, row in df_merged2.iterrows():
    trans = row["transition"]

    if row["prev_state"] == "begin":
        trans_prob = 0.3

    elif trans in ["AIS→AIS", "AIS→RF", "RF→RF", "RF→AIS"]:
        prev = df_merged2.loc[idx - 1]

        if trans == "AIS→AIS":
            time = (row["AIS_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "AIS→RF":
            time = (row["RF_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["AIS"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
                gap_counter += 1
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→RF":
            time = (row["RF_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["RF"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "RF→AIS":
            time = (row["AIS_Timestamp"] - prev["RF_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["RF"], unit=Unit.KILOMETERS)
            if time >= 5400:
                trans_prob = 0.01
            else:
                trans_prob = AIS_RF_probability(time, dist)
                
    elif row["State"] == "end":
        trans_prob = 0.05
    
    else:
        continue

    df_merged2.at[idx, "trans_prob"] = trans_prob

df_merged2

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
0,197,352002625,3,2024-01-25 03:23:05,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN
1,197,352002625,3,2024-01-25 03:23:06,2024-01-25 03:23:06,NaT,"[33.71173, -118.20001]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-25 03:23:05,1.0,"[33.71173, -118.20001]",None,None,begin,begin→AIS,0.300000
2,197,352002625,3,2024-01-25 03:26:06,2024-01-25 03:26:06,NaT,"[33.71167, -118.20008]",None,AIS,AIS,-1.135688,3.212010e-01,2024-01-25 03:23:06,180.0,"[33.71167, -118.20008]","[33.71173, -118.20001]",0.009297,AIS,AIS→AIS,0.864980
3,197,352002625,3,2024-01-25 03:29:06,2024-01-25 03:29:06,NaT,"[33.71158, -118.20017]",None,AIS,AIS,-1.172767,3.095094e-01,2024-01-25 03:26:06,180.0,"[33.71158, -118.20017]","[33.71167, -118.20008]",0.013017,AIS,AIS→AIS,0.864771
4,197,352002625,3,2024-01-25 03:32:06,2024-01-25 03:32:06,NaT,"[33.7115, -118.20021]",None,AIS,AIS,-1.209843,2.982440e-01,2024-01-25 03:29:06,180.0,"[33.7115, -118.20021]","[33.71158, -118.20017]",0.009634,AIS,AIS→AIS,0.864961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,197,352002625,3,2024-01-26 03:09:27,2024-01-26 03:09:27,NaT,"[33.72958, -118.25682]",None,AIS,AIS,-14.619515,4.475332e-07,2024-01-26 03:06:27,180.0,"[33.72958, -118.25682]","[33.72961, -118.25675]",0.007282,AIS,AIS→AIS,0.865093
348,197,352002625,3,2024-01-26 03:12:27,2024-01-26 03:12:27,NaT,"[33.72962, -118.25679]",None,AIS,AIS,-14.645162,4.362014e-07,2024-01-26 03:09:27,180.0,"[33.72962, -118.25679]","[33.72958, -118.25682]",0.005242,AIS,AIS→AIS,0.865208
349,197,352002625,3,2024-01-26 03:15:27,2024-01-26 03:15:27,NaT,"[33.72958, -118.25677]",None,AIS,AIS,-14.670808,4.251566e-07,2024-01-26 03:12:27,180.0,"[33.72958, -118.25677]","[33.72962, -118.25679]",0.004817,AIS,AIS→AIS,0.865232
350,197,352002625,3,2024-01-26 03:18:27,2024-01-26 03:18:27,NaT,"[33.7296, -118.2568]",None,AIS,AIS,-14.696455,4.143914e-07,2024-01-26 03:15:27,180.0,"[33.7296, -118.2568]","[33.72958, -118.25677]",0.003556,AIS,AIS→AIS,0.865303
351,197,352002625,3,2024-01-26 03:18:28,NaT,NaT,None,None,end,end,-17.692187,2.071957e-08,2024-01-26 03:18:27,1.0,None,"[33.7296, -118.2568]",None,AIS,AIS→end,0.050000

In [16]:
df = test_set[test_set["TrackID"] == 164]
match_rows = df[df["State"] == "M"]

ais_rows = match_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

rf_rows = match_rows.copy()
rf_rows["AIS"] = None
rf_rows["AIS_Timestamp"] = pd.NaT
rf_rows["Timestamp"] = rf_rows["RF_Timestamp"]
rf_rows["State"] = "RF"

df = df[(df["State"] != "M") & (df["State"] != "RF")]
df = pd.concat([df, ais_rows, rf_rows.iloc[0:1]], ignore_index=True)
df = df.sort_values(by=["Timestamp"]).reset_index(drop=True) 

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged = df.copy().reset_index(drop=True)
df_merged["BestPathState"] = df_path["State"]
df_merged["LogProb"] = df_path["LogProb"]
df_merged["Probability"] = np.exp(df_path["LogProb"])

df_merged["prev_Timestamp"] = df_merged["Timestamp"].shift(1)
df_merged["delta_time_sec"] = (df_merged["Timestamp"] - df_merged["prev_Timestamp"]).dt.total_seconds()

df_merged["coord"] = df_merged["AIS"].combine_first(df_merged["RF"])
df_merged["prev_coord"] = df_merged["coord"].shift(1)
df_merged["distance_km"] = None  

for idx, row in df_merged.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged.at[idx, "distance_km"] = dist
df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km
0,164,316009457,2,2024-01-03 00:01:08,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None
1,164,316009457,2,2024-01-03 00:01:09,2024-01-03 00:01:09,NaT,"[43.26082, -82.44656]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:01:08,1.0,"[43.26082, -82.44656]",None,None
2,164,316009457,2,2024-01-03 00:02:59,2024-01-03 00:02:59,NaT,"[43.25506, -82.44536]",None,AIS,AIS,-1.124278,3.248868e-01,2024-01-03 00:01:09,110.0,"[43.25506, -82.44536]","[43.26082, -82.44656]",0.647814
3,164,316009457,2,2024-01-03 00:04:09,2024-01-03 00:04:09,NaT,"[43.2514, -82.44465]",None,AIS,AIS,-1.149946,3.166538e-01,2024-01-03 00:02:59,70.0,"[43.2514, -82.44465]","[43.25506, -82.44536]",0.411016
4,164,316009457,2,2024-01-03 00:05:20,2024-01-03 00:05:20,NaT,"[43.24775, -82.4439]",None,AIS,AIS,-1.175615,3.086291e-01,2024-01-03 00:04:09,71.0,"[43.24775, -82.4439]","[43.2514, -82.44465]",0.410383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,164,316009457,2,2024-01-03 23:56:49,2024-01-03 23:56:49,NaT,"[42.26315, -83.10541]",None,AIS,AIS,-35.616248,3.404552e-16,2024-01-03 23:55:40,69.0,"[42.26315, -83.10541]","[42.26315, -83.10539]",0.001646
918,164,316009457,2,2024-01-03 23:58:00,2024-01-03 23:58:00,NaT,"[42.26315, -83.10541]",None,AIS,AIS,-35.641895,3.318346e-16,2024-01-03 23:56:49,71.0,"[42.26315, -83.10541]","[42.26315, -83.10541]",0.0
919,164,316009457,2,2024-01-03 23:59:01,2024-01-03 23:59:01,NaT,"[42.26315, -83.1054]",None,AIS,AIS,-35.667542,3.234324e-16,2024-01-03 23:58:00,61.0,"[42.26315, -83.1054]","[42.26315, -83.10541]",0.000823
920,164,316009457,2,2024-01-04 00:00:00,2024-01-04 00:00:00,NaT,"[42.26315, -83.1054]",None,AIS,AIS,-35.693188,3.152429e-16,2024-01-03 23:59:01,59.0,"[42.26315, -83.1054]","[42.26315, -83.1054]",0.0
921,164,316009457,2,2024-01-04 00:00:01,NaT,NaT,None,None,end,AIS,-35.718835,3.072608e-16,2024-01-04 00:00:00,1.0,None,"[42.26315, -83.1054]",None

In [12]:
AIS_RF_probability(49.0, 1.356456)

np.float64(0.8889772304874483)

In [13]:
df_merged.to_csv("juiste_sequence.csv", index=False)

In [14]:
df_merged["delta_time_sec"].mean(), df_merged["distance_km"].mean()

(np.float64(93.73832790445168), np.float64(0.15264899839240148))

In [15]:
sequence = test_set[test_set['TrackID'] == 291]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

In [16]:
path, probability, log_probs = model.viterbi(AIS_sequence, RF_sequence)

In [17]:
df = test_set[test_set["TrackID"] == 164]
match_rows = df[df["State"] == "M"]

rf_rows = match_rows.copy()
rf_rows["AIS"] = None
rf_rows["AIS_Timestamp"] = pd.NaT
rf_rows["Timestamp"] = rf_rows["RF_Timestamp"]
rf_rows["State"] = "RF"

df2 = test_set[test_set["TrackID"] == 291]

match_rows = df2[df2["State"] == "M"]

ais_rows = match_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

df2 = df2[(df2["State"] != "M") & (df2["State"] != "RF")]
df2 = pd.concat([df2, ais_rows, rf_rows[0:1]], ignore_index=True)
df2 = df2.sort_values(by=["Timestamp"]).reset_index(drop=True) 

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged = df2.copy().reset_index(drop=True)
df_merged["BestPathState"] = df_path["State"]
df_merged["LogProb"] = df_path["LogProb"]
df_merged["Probability"] = np.exp(df_path["LogProb"])

df_merged["prev_Timestamp"] = df_merged["Timestamp"].shift(1)
df_merged["delta_time_sec"] = (df_merged["Timestamp"] - df_merged["prev_Timestamp"]).dt.total_seconds()

df_merged["coord"] = df_merged["AIS"].combine_first(df_merged["RF"])
df_merged["prev_coord"] = df_merged["coord"].shift(1)
df_merged["distance_km"] = None  

for idx, row in df_merged.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged.at[idx, "distance_km"] = dist
df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km
0,291,366904890,2,2024-01-03 00:00:03,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None
1,291,366904890,2,2024-01-03 00:00:04,2024-01-03 00:00:04,NaT,"[42.27507, -83.10986]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:00:03,1.0,"[42.27507, -83.10986]",None,None
2,291,366904890,2,2024-01-03 00:01:06,2024-01-03 00:01:06,NaT,"[42.27466, -83.10859]",None,AIS,AIS,-1.124278,3.248868e-01,2024-01-03 00:00:04,62.0,"[42.27466, -83.10859]","[42.27507, -83.10986]",0.114003
3,291,366904890,2,2024-01-03 00:02:54,2024-01-03 00:02:54,NaT,"[42.27421, -83.10593]",None,AIS,AIS,-1.149946,3.166538e-01,2024-01-03 00:01:06,108.0,"[42.27421, -83.10593]","[42.27466, -83.10859]",0.224503
4,291,366904890,2,2024-01-03 00:03:57,2024-01-03 00:03:57,NaT,"[42.27449, -83.10459]",None,AIS,AIS,-1.175615,3.086291e-01,2024-01-03 00:02:54,63.0,"[42.27449, -83.10459]","[42.27421, -83.10593]",0.114563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,291,366904890,2,2024-01-03 23:55:41,2024-01-03 23:55:41,NaT,"[45.07417, -83.10874]",None,AIS,AIS,-38.257853,2.425636e-17,2024-01-03 23:54:40,61.0,"[45.07417, -83.10874]","[45.07101, -83.10774]",0.360044
1021,291,366904890,2,2024-01-03 23:56:51,2024-01-03 23:56:51,NaT,"[45.0778, -83.10986]",None,AIS,AIS,-38.283500,2.364217e-17,2024-01-03 23:55:41,70.0,"[45.0778, -83.10986]","[45.07417, -83.10874]",0.413108
1022,291,366904890,2,2024-01-03 23:58:00,2024-01-03 23:58:00,NaT,"[45.08135, -83.11099]",None,AIS,AIS,-38.309146,2.304354e-17,2024-01-03 23:56:51,69.0,"[45.08135, -83.11099]","[45.0778, -83.10986]",0.404591
1023,291,366904890,2,2024-01-03 23:59:10,2024-01-03 23:59:10,NaT,"[45.08501, -83.11218]",None,AIS,AIS,-38.334793,2.246006e-17,2024-01-03 23:58:00,70.0,"[45.08501, -83.11218]","[45.08135, -83.11099]",0.417561
1024,291,366904890,2,2024-01-03 23:59:11,NaT,NaT,None,None,end,end,-41.330525,1.123003e-18,2024-01-03 23:59:10,1.0,None,"[45.08501, -83.11218]",None

In [18]:
df = test_set[test_set["TrackID"] == 164]
match_rows = df[df["State"] == "M"]

ais_rows = match_rows.copy()
ais_rows["RF"] = None
ais_rows["RF_Timestamp"] = pd.NaT
ais_rows["State"] = "AIS"

rf_rows = match_rows.copy()
rf_rows["AIS"] = None
rf_rows["AIS_Timestamp"] = pd.NaT
rf_rows["Timestamp"] = rf_rows["RF_Timestamp"]
rf_rows["State"] = "RF"

df = df[(df["State"] != "M") & (df["State"] != "RF")]
df = pd.concat([df, ais_rows, rf_rows.iloc[0:1]], ignore_index=True)
df = df.sort_values(by=["Timestamp"]).reset_index(drop=True) 

df_path = pd.DataFrame({"State": path, "LogProb": log_probs})

df_merged = df.copy().reset_index(drop=True)
df_merged["BestPathState"] = df_path["State"]
df_merged["LogProb"] = df_path["LogProb"]
df_merged["Probability"] = np.exp(df_path["LogProb"])

df_merged["prev_Timestamp"] = df_merged["Timestamp"].shift(1)
df_merged["delta_time_sec"] = (df_merged["Timestamp"] - df_merged["prev_Timestamp"]).dt.total_seconds()

df_merged["coord"] = df_merged["AIS"].combine_first(df_merged["RF"])
df_merged["prev_coord"] = df_merged["coord"].shift(1)
df_merged["distance_km"] = None  

for idx, row in df_merged.iterrows():
    if row["coord"] is not None and row["prev_coord"] is not None:
        dist = haversine(row["prev_coord"], row["coord"], unit=Unit.KILOMETERS)
        df_merged.at[idx, "distance_km"] = dist
        
df_merged["prev_state"] = df_merged["State"].shift(1)
df_merged["transition"] = df_merged["prev_state"] + "→" + df_merged["State"]
df_merged["trans_prob"] = np.nan

for idx, row in df_merged.iterrows():
    trans = row["transition"]

    if row["prev_state"] == "begin":
        trans_prob = 0.3

    elif trans in ["AIS→AIS", "AIS→RF", "RF→RF", "RF→AIS"]:
        prev = df_merged.loc[idx - 1]

        if trans == "AIS→AIS":
            time = (row["AIS_Timestamp"] - prev["AIS_Timestamp"]).total_seconds()
            dist = haversine(row["AIS"], prev["AIS"], unit=Unit.KILOMETERS)
            if dist < 0.01 and time > 1800:
                trans_prob = 0.5
            else:
                trans_prob = AIS_RF_probability(time, dist)
        elif trans == "AIS→RF":
            time = row["RF_Timestamp"] - prev["AIS_Timestamp"]
            dist = haversine(row["RF"], prev["AIS"], unit=Unit.KILOMETERS)
            trans_prob = AIS_RF_probability(time.total_seconds(), dist)
        elif trans == "RF→RF":
            time = row["RF_Timestamp"] - prev["RF_Timestamp"]
            dist = haversine(row["RF"], prev["RF"], unit=Unit.KILOMETERS)
            trans_prob = AIS_RF_probability(time.total_seconds(), dist)
        elif trans == "RF→AIS":
            time = row["AIS_Timestamp"] - prev["RF_Timestamp"]
            dist = haversine(row["AIS"], prev["RF"], unit=Unit.KILOMETERS)
            trans_prob = AIS_RF_probability(time.total_seconds(), dist)

    elif row["State"] == "end":
        trans_prob = 0.05
    
    else:
        continue

    df_merged.at[idx, "trans_prob"] = trans_prob

df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
0,164,316009457,2,2024-01-03 00:01:08,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN
1,164,316009457,2,2024-01-03 00:01:09,2024-01-03 00:01:09,NaT,"[43.26082, -82.44656]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:01:08,1.0,"[43.26082, -82.44656]",None,None,begin,begin→AIS,0.300000
2,164,316009457,2,2024-01-03 00:02:59,2024-01-03 00:02:59,NaT,"[43.25506, -82.44536]",None,AIS,AIS,-1.124278,3.248868e-01,2024-01-03 00:01:09,110.0,"[43.25506, -82.44536]","[43.26082, -82.44656]",0.647814,AIS,AIS→AIS,0.886610
3,164,316009457,2,2024-01-03 00:04:09,2024-01-03 00:04:09,NaT,"[43.2514, -82.44465]",None,AIS,AIS,-1.149946,3.166538e-01,2024-01-03 00:02:59,70.0,"[43.2514, -82.44465]","[43.25506, -82.44536]",0.411016,AIS,AIS→AIS,0.926341
4,164,316009457,2,2024-01-03 00:05:20,2024-01-03 00:05:20,NaT,"[43.24775, -82.4439]",None,AIS,AIS,-1.175615,3.086291e-01,2024-01-03 00:04:09,71.0,"[43.24775, -82.4439]","[43.2514, -82.44465]",0.410383,AIS,AIS→AIS,0.925690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,164,316009457,2,2024-01-03 23:56:49,2024-01-03 23:56:49,NaT,"[42.26315, -83.10541]",None,AIS,AIS,-35.616248,3.404552e-16,2024-01-03 23:55:40,69.0,"[42.26315, -83.10541]","[42.26315, -83.10539]",0.001646,AIS,AIS→AIS,0.950079
918,164,316009457,2,2024-01-03 23:58:00,2024-01-03 23:58:00,NaT,"[42.26315, -83.10541]",None,AIS,AIS,-35.641895,3.318346e-16,2024-01-03 23:56:49,71.0,"[42.26315, -83.10541]","[42.26315, -83.10541]",0.0,AIS,AIS→AIS,0.948766
919,164,316009457,2,2024-01-03 23:59:01,2024-01-03 23:59:01,NaT,"[42.26315, -83.1054]",None,AIS,AIS,-35.667542,3.234324e-16,2024-01-03 23:58:00,61.0,"[42.26315, -83.1054]","[42.26315, -83.10541]",0.000823,AIS,AIS→AIS,0.955773
920,164,316009457,2,2024-01-04 00:00:00,2024-01-04 00:00:00,NaT,"[42.26315, -83.1054]",None,AIS,AIS,-35.693188,3.152429e-16,2024-01-03 23:59:01,59.0,"[42.26315, -83.1054]","[42.26315, -83.1054]",0.0,AIS,AIS→AIS,0.957238
921,164,316009457,2,2024-01-04 00:00:01,NaT,NaT,None,None,end,AIS,-35.718835,3.072608e-16,2024-01-04 00:00:00,1.0,None,"[42.26315, -83.1054]",None,AIS,AIS→end,0.050000

In [19]:
df_merged.sort_values(by=["trans_prob"], inplace=True)
df_merged

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State,BestPathState,LogProb,Probability,prev_Timestamp,delta_time_sec,coord,prev_coord,distance_km,prev_state,transition,trans_prob
160,164,316009457,2,2024-01-03 05:29:40,2024-01-03 05:29:40,NaT,"[42.45249, -82.77025]",None,AIS,AIS,-16.201736,9.197617e-08,2024-01-03 03:04:39,8701.0,"[42.45249, -82.77025]","[42.75882, -82.46882]",42.057645,AIS,AIS→AIS,0.000127
921,164,316009457,2,2024-01-04 00:00:01,NaT,NaT,None,None,end,AIS,-35.718835,3.072608e-16,2024-01-04 00:00:00,1.0,None,"[42.26315, -83.1054]",None,AIS,AIS→end,0.050000
1,164,316009457,2,2024-01-03 00:01:09,2024-01-03 00:01:09,NaT,"[43.26082, -82.44656]",None,AIS,AIS,-1.098612,3.333333e-01,2024-01-03 00:01:08,1.0,"[43.26082, -82.44656]",None,None,begin,begin→AIS,0.300000
611,164,316009457,2,2024-01-03 18:03:20,2024-01-03 18:03:20,NaT,"[42.26352, -83.10525]",None,AIS,AIS,-27.768374,8.716624e-13,2024-01-03 14:12:39,13841.0,"[42.26352, -83.10525]","[42.26351, -83.10523]",0.001986,AIS,AIS→AIS,0.500000
187,164,316009457,2,2024-01-03 06:02:20,2024-01-03 06:02:20,NaT,"[42.38829, -82.8656]",None,AIS,AIS,-16.894196,4.601972e-08,2024-01-03 05:59:41,159.0,"[42.38829, -82.8656]","[42.39352, -82.85779]",0.865786,AIS,AIS→AIS,0.843897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,164,316009457,2,2024-01-03 09:00:00,2024-01-03 09:00:00,NaT,"[42.26334, -83.10528]",None,AIS,AIS,-20.818133,9.094939e-10,2024-01-03 08:59:30,30.0,"[42.26334, -83.10528]","[42.26334, -83.1053]",0.001646,AIS,AIS→AIS,0.977926
548,164,316009457,2,2024-01-03 13:00:00,2024-01-03 13:00:00,NaT,"[42.2635, -83.10525]",None,AIS,AIS,-26.152635,4.385860e-12,2024-01-03 12:59:31,29.0,"[42.2635, -83.10525]","[42.26351, -83.10525]",0.001112,AIS,AIS→AIS,0.978682
104,164,316009457,2,2024-01-03 02:00:00,2024-01-03 02:00:00,NaT,"[42.93295, -82.45304]",None,AIS,AIS,-14.765524,3.867358e-07,2024-01-03 01:59:40,20.0,"[42.93295, -82.45304]","[42.93383, -82.45251]",0.106942,AIS,AIS→AIS,0.978992
393,164,316009457,2,2024-01-03 10:00:00,2024-01-03 10:00:00,NaT,"[42.26326, -83.10537]",None,AIS,AIS,-22.177405,2.336013e-10,2024-01-03 09:59:51,9.0,"[42.26326, -83.10537]","[42.26326, -83.10537]",0.0,AIS,AIS→AIS,0.993356
0,164,316009457,2,2024-01-03 00:01:08,NaT,NaT,None,None,begin,begin,0.000000,1.000000e+00,NaT,NaN,None,None,None,None,NaN,NaN

In [22]:
test_set[(test_set["TrackID"] == 164) & (test_set["Timestamp"] == "2024-01-03 18:03:20")].index

Index([103715], dtype='int64')

In [23]:
test_set.iloc[103715-3:103715+3]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
103712,164,316009457,2,2024-01-03 14:10:20,2024-01-03 14:10:20,NaT,"[42.26348, -83.10523]",None,AIS
103713,164,316009457,2,2024-01-03 14:11:30,2024-01-03 14:11:30,NaT,"[42.26349, -83.10524]",None,AIS
103714,164,316009457,2,2024-01-03 14:12:39,2024-01-03 14:12:39,NaT,"[42.26351, -83.10523]",None,AIS
103715,164,316009457,2,2024-01-03 18:03:20,2024-01-03 18:03:20,NaT,"[42.26352, -83.10525]",None,AIS
103716,164,316009457,2,2024-01-03 18:04:31,2024-01-03 18:04:31,NaT,"[42.2635, -83.10525]",None,AIS
103717,164,316009457,2,2024-01-03 18:05:39,2024-01-03 18:05:39,NaT,"[42.26352, -83.10525]",None,AIS

In [24]:
AIS_RF_probability(110.0, 0.647814)

np.float64(0.8866097838531733)

In [25]:
0.1

0.1

In [26]:
-(35/1025)

-0.03414634146341464

In [27]:
sequence3 = test_set[test_set['TrackID'] == 100]

AIS_sequence3 = [(time, coord) for time, coord in zip(sequence3["AIS_Timestamp"], sequence3["AIS"]) 
                if pd.notna(time) and coord is not None]

RF_sequence3 = [(time, coord) for time, coord in zip(sequence3["RF_Timestamp"], sequence3["RF"]) 
               if pd.notna(time) and coord is not None]

In [28]:
path3, probability3, log_probs3 = model.viterbi(AIS_sequence3, RF_sequence3)

In [29]:
RF_M_indexes_pred_path3 = [(i, state) for i, state in enumerate(path3) if state in {"RF", "M"}]
RF_M_indexes_real_path3 = [(i, state) for i, state in enumerate(sequence3["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path3}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path3}")

The indexes of RF and/or M of predicted path are: [(110, 'RF'), (286, 'RF')],
The indexes of RF and/or M of the real path are: [(110, 'RF'), (286, 'RF')]

In [30]:
sequence = test_set[test_set['TrackID'] == 291]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

AIS_sequence

[(Timestamp('2024-01-03 00:00:04'), array([ 42.27507, -83.10986])),
 (Timestamp('2024-01-03 00:01:06'), array([ 42.27466, -83.10859])),
 (Timestamp('2024-01-03 00:02:54'), array([ 42.27421, -83.10593])),
 (Timestamp('2024-01-03 00:03:57'), array([ 42.27449, -83.10459])),
 (Timestamp('2024-01-03 00:05:00'), array([ 42.2751 , -83.10387])),
 (Timestamp('2024-01-03 00:06:03'), array([ 42.27593, -83.10332])),
 (Timestamp('2024-01-03 00:07:14'), array([ 42.27718, -83.10256])),
 (Timestamp('2024-01-03 00:08:22'), array([ 42.27871, -83.10181])),
 (Timestamp('2024-01-03 00:09:33'), array([ 42.28057, -83.10091])),
 (Timestamp('2024-01-03 00:10:43'), array([ 42.2826 , -83.09994])),
 (Timestamp('2024-01-03 00:11:53'), array([ 42.28475, -83.09887])),
 (Timestamp('2024-01-03 00:13:03'), array([ 42.28697, -83.09778])),
 (Timestamp('2024-01-03 00:14:13'), array([ 42.28917, -83.09656])),
 (Timestamp('2024-01-03 00:15:23'), array([ 42.29139, -83.09532])),
 (Timestamp('2024-01-03 00:16:33'), array([ 42.29341, -83.0941 ])),
 (Timestamp('2024-01-03 00:17:42'), array([ 42.29521, -83.09305])),
 (Timestamp('2024-01-03 00:18:44'), array([ 42.29656, -83.09224])),
 (Timestamp('2024-01-03 00:19:53'), array([ 42.29786, -83.09144])),
 (Timestamp('2024-01-03 00:21:04'), array([ 42.29899, -83.09077])),
 (Timestamp('2024-01-03 00:22:12'), array([ 42.29995, -83.09027])),
 (Timestamp('2024-01-03 00:23:23'), array([ 42.30077, -83.08987])),
 (Timestamp('2024-01-03 00:24:24'), array([ 42.30135, -83.08958])),
 (Timestamp('2024-01-03 00:25:32'), array([ 42.30181, -83.08931])),
 (Timestamp('2024-01-03 00:26:43'), array([ 42.30214, -83.08912])),
 (Timestamp('2024-01-03 00:27:54'), array([ 42.30242, -83.08892])),
 (Timestamp('2024-01-03 00:29:02'), array([ 42.30265, -83.08874])),
 (Timestamp('2024-01-03 00:30:12'), array([ 42.30286, -83.08857])),
 (Timestamp('2024-01-03 00:31:24'), array([ 42.30302, -83.08845])),
 (Timestamp('2024-01-03 00:32:32'), array([ 42.30311, -83.08834])),
 (Timestamp('2024-01-03 00:33:43'), array([ 42.30319, -83.08827])),
 (Timestamp('2024-01-03 00:34:53'), array([ 42.3032 , -83.08829])),
 (Timestamp('2024-01-03 00:36:03'), array([ 42.3032 , -83.08828])),
 (Timestamp('2024-01-03 00:39:01'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 00:42:00'), array([ 42.30321, -83.08833])),
 (Timestamp('2024-01-03 00:44:59'), array([ 42.30321, -83.08833])),
 (Timestamp('2024-01-03 00:47:59'), array([ 42.3032 , -83.08832])),
 (Timestamp('2024-01-03 00:51:01'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 00:53:57'), array([ 42.30322, -83.08831])),
 (Timestamp('2024-01-03 00:57:00'), array([ 42.3032 , -83.08834])),
 (Timestamp('2024-01-03 00:59:59'), array([ 42.30321, -83.0883 ])),
 (Timestamp('2024-01-03 01:02:59'), array([ 42.30322, -83.08832])),
 (Timestamp('2024-01-03 01:06:01'), array([ 42.30321, -83.08828])),
 (Timestamp('2024-01-03 01:08:59'), array([ 42.30319, -83.08831])),
 (Timestamp('2024-01-03 01:11:59'), array([ 42.3032, -83.0883])),
 (Timestamp('2024-01-03 01:15:00'), array([ 42.30322, -83.0883 ])),
 (Timestamp('2024-01-03 01:17:58'), array([ 42.3032 , -83.08829])),
 (Timestamp('2024-01-03 01:21:02'), array([ 42.3032, -83.0883])),
 (Timestamp('2024-01-03 01:24:01'), array([ 42.30318, -83.08832])),
 (Timestamp('2024-01-03 01:27:04'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 01:30:03'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 01:33:04'), array([ 42.30322, -83.08829])),
 (Timestamp('2024-01-03 01:36:04'), array([ 42.3032 , -83.08832])),
 (Timestamp('2024-01-03 01:39:03'), array([ 42.30321, -83.08833])),
 (Timestamp('2024-01-03 01:42:05'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 01:45:04'), array([ 42.3032 , -83.08833])),
 (Timestamp('2024-01-03 01:48:03'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 01:51:05'), array([ 42.30322, -83.08834])),
 (Timestamp('2024-01-03 01:54:03'), array([ 42.30322, -83.08833])),
 (Timestamp('2024-01-03 01:57:05'), array([ 42.3032 , -83.08833])),
 (Timestamp('2024-01-03 02:00:05'), array([ 42.30323, -83.08832])),
 (Timestamp('2024-01-03 02:06:05'), array([ 42.30322, -83.08833])),
 (Timestamp('2024-01-03 02:09:05'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 02:12:04'), array([ 42.30323, -83.08831])),
 (Timestamp('2024-01-03 02:15:05'), array([ 42.30323, -83.08832])),
 (Timestamp('2024-01-03 02:18:05'), array([ 42.30323, -83.0883 ])),
 (Timestamp('2024-01-03 02:21:03'), array([ 42.3032, -83.0883])),
 (Timestamp('2024-01-03 02:24:04'), array([ 42.30323, -83.08831])),
 (Timestamp('2024-01-03 02:27:02'), array([ 42.30322, -83.0883 ])),
 (Timestamp('2024-01-03 02:30:05'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 02:33:01'), array([ 42.3032 , -83.08828])),
 (Timestamp('2024-01-03 02:36:03'), array([ 42.3032 , -83.08828])),
 (Timestamp('2024-01-03 02:38:59'), array([ 42.30323, -83.08832])),
 (Timestamp('2024-01-03 02:42:05'), array([ 42.30321, -83.08831])),
 (Timestamp('2024-01-03 02:51:03'), array([ 42.30323, -83.08831])),
 (Timestamp('2024-01-03 02:53:59'), array([ 42.30321, -83.08833])),
 (Timestamp('2024-01-03 02:57:04'), array([ 42.30321, -83.08831])),
 (Timestamp('2024-01-03 03:00:00'), array([ 42.30319, -83.0883 ])),
 (Timestamp('2024-01-03 03:03:05'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 03:06:01'), array([ 42.30319, -83.08828])),
 (Timestamp('2024-01-03 03:09:06'), array([ 42.30319, -83.08829])),
 (Timestamp('2024-01-03 03:12:00'), array([ 42.30321, -83.0883 ])),
 (Timestamp('2024-01-03 03:14:56'), array([ 42.30319, -83.08832])),
 (Timestamp('2024-01-03 03:17:59'), array([ 42.30321, -83.0883 ])),
 (Timestamp('2024-01-03 03:20:59'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 03:24:01'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 03:26:59'), array([ 42.30322, -83.08829])),
 (Timestamp('2024-01-03 03:30:03'), array([ 42.30321, -83.08831])),
 (Timestamp('2024-01-03 03:32:58'), array([ 42.30319, -83.08833])),
 (Timestamp('2024-01-03 03:36:03'), array([ 42.3032 , -83.08831])),
 (Timestamp('2024-01-03 03:42:02'), array([ 42.30321, -83.0883 ])),
 (Timestamp('2024-01-03 03:45:01'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 03:48:04'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 03:51:02'), array([ 42.3032 , -83.08829])),
 (Timestamp('2024-01-03 03:54:05'), array([ 42.30322, -83.08829])),
 (Timestamp('2024-01-03 03:57:02'), array([ 42.3032 , -83.08828])),
 (Timestamp('2024-01-03 04:00:06'), array([ 42.30321, -83.08832])),
 (Timestamp('2024-01-03 04:03:04'), array([ 42.30322, -83.08831])),
 (Timestamp('2024-01-03 04:04:10'), array([ 42.30323, -83.0883 ])),
 (Timestamp('2024-01-03 04:05:20'), array([ 42.30318, -83.08822])),
 (Timestamp('2024-01-03 04:06:39'), array([ 42.30318, -83.0878 ])),
 (Timestamp('2024-01-03 04:07:50'), array([ 42.3034 , -83.08709])),
 (Timestamp('2024-01-03 04:08:51'), array([ 42.30379, -83.08627])),
 (Timestamp('2024-01-03 04:10:00'), array([ 42.30444, -83.08511])),
 (Timestamp('2024-01-03 04:11:09'), array([ 42.3053 , -83.08369])),
 (Timestamp('2024-01-03 04:12:21'), array([ 42.30635, -83.08203])),
 (Timestamp('2024-01-03 04:13:31'), array([ 42.30756, -83.08022])),
 (Timestamp('2024-01-03 04:14:39'), array([ 42.30886, -83.07831])),
 (Timestamp('2024-01-03 04:15:40'), array([ 42.31002, -83.07649])),
 (Timestamp('2024-01-03 04:16:49'), array([ 42.31154, -83.07424])),
 (Timestamp('2024-01-03 04:17:50'), array([ 42.31278, -83.07209])),
 (Timestamp('2024-01-03 04:19:00'), array([ 42.31412, -83.06928])),
 (Timestamp('2024-01-03 04:20:10'), array([ 42.3152 , -83.06628])),
 (Timestamp('2024-01-03 04:21:20'), array([ 42.31626, -83.06312])),
 (Timestamp('2024-01-03 04:22:30'), array([ 42.31737, -83.05984])),
 (Timestamp('2024-01-03 04:23:41'), array([ 42.3186 , -83.05635])),
 (Timestamp('2024-01-03 04:24:50'), array([ 42.3198 , -83.05298])),
 (Timestamp('2024-01-03 04:25:51'), array([ 42.32081, -83.04973])),
 (Timestamp('2024-01-03 04:27:01'), array([ 42.32196, -83.04585])),
 (Timestamp('2024-01-03 04:28:03'), array([ 42.32295, -83.0423 ])),
 (Timestamp('2024-01-03 04:29:10'), array([ 42.32368, -83.03839])),
 (Timestamp('2024-01-03 04:30:20'), array([ 42.32451, -83.03405])),
 (Timestamp('2024-01-03 04:31:31'), array([ 42.32533, -83.02964])),
 (Timestamp('2024-01-03 04:32:41'), array([ 42.32612, -83.02522])),
 (Timestamp('2024-01-03 04:33:51'), array([ 42.32693, -83.02084])),
 (Timestamp('2024-01-03 04:35:01'), array([ 42.3278 , -83.01645])),
 (Timestamp('2024-01-03 04:36:10'), array([ 42.3284 , -83.01213])),
 (Timestamp('2024-01-03 04:37:20'), array([ 42.32874, -83.00771])),
 (Timestamp('2024-01-03 04:38:30'), array([ 42.32916, -83.00319])),
 (Timestamp('2024-01-03 04:39:41'), array([ 42.32958, -82.99874])),
 (Timestamp('2024-01-03 04:40:50'), array([ 42.32995, -82.99438])),
 (Timestamp('2024-01-03 04:41:51'), array([ 42.33028, -82.99053])),
 (Timestamp('2024-01-03 04:43:01'), array([ 42.33083, -82.98611])),
 (Timestamp('2024-01-03 04:44:11'), array([ 42.33169, -82.98188])),
 (Timestamp('2024-01-03 04:45:21'), array([ 42.33259, -82.97762])),
 (Timestamp('2024-01-03 04:46:30'), array([ 42.33348, -82.97343])),
 (Timestamp('2024-01-03 04:47:39'), array([ 42.33448, -82.96924])),
 (Timestamp('2024-01-03 04:48:45'), array([ 42.33551, -82.96532])),
 (Timestamp('2024-01-03 04:49:50'), array([ 42.33692, -82.96184])),
 (Timestamp('2024-01-03 04:50:57'), array([ 42.33856, -82.95834])),
 (Timestamp('2024-01-03 04:52:00'), array([ 42.34046, -82.95542])),
 (Timestamp('2024-01-03 04:53:11'), array([ 42.34276, -82.95232])),
 (Timestamp('2024-01-03 04:54:21'), array([ 42.34505, -82.9492 ])),
 (Timestamp('2024-01-03 04:55:29'), array([ 42.34738, -82.94611])),
 (Timestamp('2024-01-03 04:56:32'), array([ 42.34953, -82.94326])),
 (Timestamp('2024-01-03 04:57:34'), array([ 42.3513 , -82.94021])),
 (Timestamp('2024-01-03 04:58:40'), array([ 42.35277, -82.93652])),
 (Timestamp('2024-01-03 04:59:49'), array([ 42.35414, -82.93246])),
 (Timestamp('2024-01-03 05:00:10'), array([ 42.35455, -82.93131])),
 (Timestamp('2024-01-03 05:01:21'), array([ 42.3559 , -82.92709])),
 (Timestamp('2024-01-03 05:02:29'), array([ 42.35721, -82.92288])),
 (Timestamp('2024-01-03 05:03:40'), array([ 42.3585 , -82.91857])),
 (Timestamp('2024-01-03 05:04:51'), array([ 42.35984, -82.91412])),
 (Timestamp('2024-01-03 05:06:00'), array([ 42.36113, -82.90975])),
 (Timestamp('2024-01-03 05:07:11'), array([ 42.36249, -82.90524])),
 (Timestamp('2024-01-03 05:08:12'), array([ 42.36407, -82.9017 ])),
 (Timestamp('2024-01-03 05:09:20'), array([ 42.36633, -82.8982 ])),
 (Timestamp('2024-01-03 05:10:30'), array([ 42.36868, -82.89471])),
 (Timestamp('2024-01-03 05:11:39'), array([ 42.37108, -82.89119])),
 (Timestamp('2024-01-03 05:12:49'), array([ 42.37349, -82.88759])),
 (Timestamp('2024-01-03 05:14:00'), array([ 42.37591, -82.88399])),
 (Timestamp('2024-01-03 05:15:10'), array([ 42.37836, -82.88031])),
 (Timestamp('2024-01-03 05:16:20'), array([ 42.38078, -82.87673])),
 (Timestamp('2024-01-03 05:17:29'), array([ 42.38324, -82.87305])),
 (Timestamp('2024-01-03 05:18:40'), array([ 42.38576, -82.8693 ])),
 (Timestamp('2024-01-03 05:19:51'), array([ 42.38823, -82.86553])),
 (Timestamp('2024-01-03 05:21:00'), array([ 42.39072, -82.86182])),
 (Timestamp('2024-01-03 05:22:10'), array([ 42.3932 , -82.85803])),
 (Timestamp('2024-01-03 05:23:19'), array([ 42.3957 , -82.85421])),
 (Timestamp('2024-01-03 05:24:30'), array([ 42.39825, -82.85034])),
 (Timestamp('2024-01-03 05:25:41'), array([ 42.40073, -82.84645])),
 (Timestamp('2024-01-03 05:26:50'), array([ 42.40324, -82.84259])),
 (Timestamp('2024-01-03 05:28:01'), array([ 42.40577, -82.83872])),
 (Timestamp('2024-01-03 05:29:11'), array([ 42.40832, -82.83485])),
 (Timestamp('2024-01-03 05:30:20'), array([ 42.41085, -82.83109])),
 (Timestamp('2024-01-03 05:31:30'), array([ 42.41345, -82.82725])),
 (Timestamp('2024-01-03 05:32:41'), array([ 42.41606, -82.82331])),
 (Timestamp('2024-01-03 05:33:51'), array([ 42.41862, -82.81941])),
 (Timestamp('2024-01-03 05:35:01'), array([ 42.42122, -82.8155 ])),
 (Timestamp('2024-01-03 05:36:10'), array([ 42.42384, -82.81164])),
 (Timestamp('2024-01-03 05:37:20'), array([ 42.42645, -82.80783])),
 (Timestamp('2024-01-03 05:38:30'), array([ 42.42908, -82.80395])),
 (Timestamp('2024-01-03 05:39:41'), array([ 42.43171, -82.79996])),
 (Timestamp('2024-01-03 05:40:50'), array([ 42.43441, -82.79618])),
 (Timestamp('2024-01-03 05:42:00'), array([ 42.43709, -82.79247])),
 (Timestamp('2024-01-03 05:43:11'), array([ 42.43984, -82.78859])),
 (Timestamp('2024-01-03 05:44:19'), array([ 42.44246, -82.78478])),
 (Timestamp('2024-01-03 05:45:30'), array([ 42.44517, -82.78094])),
 (Timestamp('2024-01-03 05:46:39'), array([ 42.44776, -82.77704])),
 (Timestamp('2024-01-03 05:47:49'), array([ 42.45046, -82.77304])),
 (Timestamp('2024-01-03 05:48:59'), array([ 42.45315, -82.76909])),
 (Timestamp('2024-01-03 05:50:00'), array([ 42.45541, -82.76568])),
 (Timestamp('2024-01-03 05:51:11'), array([ 42.45807, -82.76162])),
 (Timestamp('2024-01-03 05:52:20'), array([ 42.46066, -82.75768])),
 (Timestamp('2024-01-03 05:53:27'), array([ 42.46323, -82.75377])),
 (Timestamp('2024-01-03 05:54:31'), array([ 42.46585, -82.75055])),
 (Timestamp('2024-01-03 05:55:50'), array([ 42.46921, -82.7466 ])),
 (Timestamp('2024-01-03 05:57:00'), array([ 42.47221, -82.74313])),
 (Timestamp('2024-01-03 05:58:11'), array([ 42.47525, -82.73957])),
 (Timestamp('2024-01-03 05:59:21'), array([ 42.47824, -82.73607])),
 (Timestamp('2024-01-03 06:00:00'), array([ 42.4799 , -82.73411])),
 (Timestamp('2024-01-03 06:02:21'), array([ 42.48591, -82.727  ])),
 (Timestamp('2024-01-03 06:03:30'), array([ 42.48888, -82.72356])),
 (Timestamp('2024-01-03 06:04:40'), array([ 42.49182, -82.72001])),
 (Timestamp('2024-01-03 06:05:50'), array([ 42.49475, -82.71649])),
 (Timestamp('2024-01-03 06:07:00'), array([ 42.49774, -82.71307])),
 (Timestamp('2024-01-03 06:08:10'), array([ 42.50064, -82.70968])),
 (Timestamp('2024-01-03 06:09:20'), array([ 42.50348, -82.70625])),
 (Timestamp('2024-01-03 06:10:30'), array([ 42.50643, -82.70281])),
 (Timestamp('2024-01-03 06:11:31'), array([ 42.5089 , -82.69992])),
 (Timestamp('2024-01-03 06:12:41'), array([ 42.51127, -82.69614])),
 (Timestamp('2024-01-03 06:13:49'), array([ 42.51335, -82.69233])),
 (Timestamp('2024-01-03 06:14:53'), array([ 42.51514, -82.68894])),
 (Timestamp('2024-01-03 06:16:00'), array([ 42.51663, -82.68512])),
 (Timestamp('2024-01-03 06:17:10'), array([ 42.51802, -82.68121])),
 (Timestamp('2024-01-03 06:18:21'), array([ 42.51949, -82.67716])),
 (Timestamp('2024-01-03 06:19:29'), array([ 42.52087, -82.67326])),
 (Timestamp('2024-01-03 06:20:40'), array([ 42.52234, -82.66924])),
 (Timestamp('2024-01-03 06:21:50'), array([ 42.52377, -82.66531])),
 (Timestamp('2024-01-03 06:23:00'), array([ 42.52519, -82.66141])),
 (Timestamp('2024-01-03 06:24:10'), array([ 42.52662, -82.65753])),
 (Timestamp('2024-01-03 06:25:19'), array([ 42.52806, -82.65359])),
 (Timestamp('2024-01-03 06:26:31'), array([ 42.52947, -82.64955])),
 (Timestamp('2024-01-03 06:27:40'), array([ 42.53092, -82.64558])),
 (Timestamp('2024-01-03 06:28:51'), array([ 42.53236, -82.64155])),
 (Timestamp('2024-01-03 06:30:10'), array([ 42.53396, -82.63701])),
 (Timestamp('2024-01-03 06:31:31'), array([ 42.53555, -82.6324 ])),
 (Timestamp('2024-01-03 06:32:41'), array([ 42.53695, -82.62846])),
 (Timestamp('2024-01-03 06:33:51'), array([ 42.53836, -82.62454])),
 (Timestamp('2024-01-03 06:35:11'), array([ 42.53993, -82.62007])),
 (Timestamp('2024-01-03 06:36:30'), array([ 42.5415 , -82.61575])),
 (Timestamp('2024-01-03 06:37:41'), array([ 42.54289, -82.61183])),
 (Timestamp('2024-01-03 06:38:51'), array([ 42.54422, -82.60802])),
 (Timestamp('2024-01-03 06:40:01'), array([ 42.54557, -82.60429])),
 (Timestamp('2024-01-03 06:41:11'), array([ 42.54691, -82.6005 ])),
 (Timestamp('2024-01-03 06:42:21'), array([ 42.54839, -82.59652])),
 (Timestamp('2024-01-03 06:43:30'), array([ 42.54982, -82.59249])),
 (Timestamp('2024-01-03 06:44:34'), array([ 42.55133, -82.58877])),
 (Timestamp('2024-01-03 06:45:38'), array([ 42.55338, -82.58611])),
 (Timestamp('2024-01-03 06:46:41'), array([ 42.55577, -82.58463])),
 (Timestamp('2024-01-03 06:47:50'), array([ 42.55855, -82.58314])),
 (Timestamp('2024-01-03 06:49:01'), array([ 42.56157, -82.58163])),
 (Timestamp('2024-01-03 06:50:07'), array([ 42.56441, -82.58028])),
 (Timestamp('2024-01-03 06:51:08'), array([ 42.56684, -82.57855])),
 (Timestamp('2024-01-03 06:52:09'), array([ 42.56898, -82.57621])),
 (Timestamp('2024-01-03 06:53:20'), array([ 42.5711, -82.5731])),
 (Timestamp('2024-01-03 06:54:31'), array([ 42.57332, -82.5698 ])),
 (Timestamp('2024-01-03 06:55:40'), array([ 42.57557, -82.56657])),
 (Timestamp('2024-01-03 06:56:51'), array([ 42.57786, -82.56322])),
 (Timestamp('2024-01-03 06:58:01'), array([ 42.58009, -82.55994])),
 (Timestamp('2024-01-03 06:59:09'), array([ 42.58232, -82.55671])),
 (Timestamp('2024-01-03 07:00:01'), array([ 42.58416, -82.55455])),
 (Timestamp('2024-01-03 07:01:11'), array([ 42.58678, -82.55176])),
 (Timestamp('2024-01-03 07:02:20'), array([ 42.58935, -82.54903])),
 (Timestamp('2024-01-03 07:03:29'), array([ 42.59197, -82.54622])),
 (Timestamp('2024-01-03 07:04:30'), array([ 42.59391, -82.54354])),
 (Timestamp('2024-01-03 07:05:41'), array([ 42.596  , -82.54019])),
 (Timestamp('2024-01-03 07:06:50'), array([ 42.59807, -82.53688])),
 (Timestamp('2024-01-03 07:07:51'), array([ 42.5999 , -82.53398])),
 (Timestamp('2024-01-03 07:09:01'), array([ 42.602  , -82.53062])),
 (Timestamp('2024-01-03 07:10:11'), array([ 42.6041 , -82.52723])),
 (Timestamp('2024-01-03 07:11:14'), array([ 42.60606, -82.52419])),
 (Timestamp('2024-01-03 07:12:17'), array([ 42.60831, -82.52184])),
 (Timestamp('2024-01-03 07:13:19'), array([ 42.61079, -82.52026])),
 (Timestamp('2024-01-03 07:14:30'), array([ 42.6138, -82.5185])),
 (Timestamp('2024-01-03 07:15:41'), array([ 42.61682, -82.51675])),
 (Timestamp('2024-01-03 07:16:50'), array([ 42.6198 , -82.51509])),
 (Timestamp('2024-01-03 07:17:56'), array([ 42.62275, -82.51359])),
 (Timestamp('2024-01-03 07:19:00'), array([ 42.62575, -82.51275])),
 (Timestamp('2024-01-03 07:20:10'), array([ 42.62909, -82.51224])),
 (Timestamp('2024-01-03 07:21:20'), array([ 42.63246, -82.5117 ])),
 (Timestamp('2024-01-03 07:22:31'), array([ 42.63575, -82.51109])),
 (Timestamp('2024-01-03 07:23:40'), array([ 42.63895, -82.51049])),
 (Timestamp('2024-01-03 07:24:51'), array([ 42.64228, -82.50992])),
 (Timestamp('2024-01-03 07:26:01'), array([ 42.64561, -82.50967])),
 (Timestamp('2024-01-03 07:27:09'), array([ 42.64889, -82.50974])),
 (Timestamp('2024-01-03 07:28:20'), array([ 42.65219, -82.50976])),
 (Timestamp('2024-01-03 07:29:21'), array([ 42.65511, -82.50982])),
 (Timestamp('2024-01-03 07:30:30'), array([ 42.65842, -82.5099 ])),
 (Timestamp('2024-01-03 07:31:41'), array([ 42.66181, -82.51003])),
 (Timestamp('2024-01-03 07:32:44'), array([ 42.66471, -82.50984])),
 (Timestamp('2024-01-03 07:33:51'), array([ 42.6677 , -82.50905])),
 (Timestamp('2024-01-03 07:35:00'), array([ 42.67085, -82.50818])),
 (Timestamp('2024-01-03 07:36:09'), array([ 42.6741 , -82.50734])),
 (Timestamp('2024-01-03 07:37:20'), array([ 42.67739, -82.50648])),
 (Timestamp('2024-01-03 07:38:21'), array([ 42.68008, -82.50543])),
 (Timestamp('2024-01-03 07:39:30'), array([ 42.68323, -82.50414])),
 (Timestamp('2024-01-03 07:40:40'), array([ 42.6864 , -82.50281])),
 (Timestamp('2024-01-03 07:41:49'), array([ 42.68959, -82.50151])),
 (Timestamp('2024-01-03 07:42:50'), array([ 42.69233, -82.5004 ])),
 (Timestamp('2024-01-03 07:44:00'), array([ 42.69547, -82.49905])),
 (Timestamp('2024-01-03 07:45:09'), array([ 42.69857, -82.49773])),
 (Timestamp('2024-01-03 07:46:11'), array([ 42.70126, -82.49662])),
 (Timestamp('2024-01-03 07:47:20'), array([ 42.70414, -82.495  ])),
 (Timestamp('2024-01-03 07:48:31'), array([ 42.70712, -82.49335])),