In [13]:
# Import packages

import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# Load raw data 
df_AIS = pd.read_pickle("../data/raw/AIS_01_2024.pkl")
df_AIS.head(5)

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
0,338075892,2024-01-01T00:00:03,43.65322,-70.25298,0.0,358.8,511.0,PILOT BOAT SPRING PT,NaN,WDB8945,90.0,0.0,0.0,0.0,0.0,90.0,A
1,367669550,2024-01-01T00:00:04,46.20031,-123.38573,0.0,281.9,141.0,ALASKA CHALLENGER,IMO7938024,WDH9586,30.0,15.0,30.0,8.0,0.0,30.0,A
2,367118980,2024-01-01T00:00:06,29.98534,-90.40674,0.0,30.1,296.0,CAPT J A MORGAN,IMO1186680,WDD2725,31.0,12.0,115.0,34.0,3.0,57.0,A
3,367177840,2024-01-01T00:00:05,39.88654,-75.17649,0.0,304.4,511.0,BART TURECAMO,IMO7338808,WBR4464,52.0,15.0,33.0,5.0,0.0,52.0,A
4,367305420,2024-01-01T00:00:06,18.33273,-64.95229,0.0,332.6,511.0,DOROTHY MORAN,IMO7716995,WXU4654,52.0,0.0,33.0,11.0,0.0,52.0,A

In [3]:
# Length of raw data 
print(f"Number of AIS observations: {len(df_AIS)}")

Number of AIS observations: 221958517

In [19]:
# Different type of vessels
vessel_type_codes = df_AIS["Cargo"].unique()

json_path = "../config/mappings/vessel_type_names.json"
with open(json_path, "r") as f:
    vessel_type_names = json.load(f)

vessel_type_codes, vessel_type_names

(array([ 90.,  30.,  57.,  52.,  nan,  80.,  31.,  34.,  60.,  71.,  51.,
         33.,  79.,  37.,   0.,  70.,  55.,  35.,  40.,  99.,  89.,  50.,
         59.,  32.,  82.,   3.,  39.,  69.,   6.,  20.,  53.,  22.,  97.,
         65.,  72.,  66.,  91.,  56.,  95.,   5.,  74.,  12.,  73.,  10.,
         85.,  54.,   7.,  49.,  68.,  81.,  36.,  84.,  42.,  21.,   1.,
          9.,  58., 136.,  11.,  98.,   2.,  76.,  38.,  62.,  27.,  43.,
         67.,  29.,  75.,  23.,  96.,  88., 118.,  61.,  94.,  83.,  25.,
         19.,  77.,  24.,  63.,  78.,   4., 255.,  18.,  16.,  87.,   8.,
         44.,  15., 200., 168., 159.,  26., 188., 178., 154.,  41.,  92.,
         93.,  86.]),
 {'30': 'Fishing',
  '31': 'Towing',
  '33': 'Dredging',
  '34': 'Diving',
  '35': 'Military',
  '36': 'Yachting',
  '40': 'Highspeed',
  '50': 'Pilot',
  '51': 'Search and Rescue (SAR)',
  '52': 'Tug',
  '53': 'PortTender',
  '54': 'Antipollution',
  '55': 'Law',
  '56': 'Local',
  '57': 'Local',
  '58': 'Medical',
  '59': 'Notengaged',
  '60': 'Passenger',
  '70': 'Cargo',
  '80': 'Tanker'})

In [8]:
# Load filtered cargo data
df_cargo = pd.read_parquet("../data/processed/cargo_vessels.parquet")
df_cargo.head(5)

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
49,367121040,2024-01-01 00:00:03,41.54617,-82.72934,0.0,5.5,184.0,AMERICAN COURAGE,IMO7634226,WDD2879,70.0,0.0,194.0,21.0,0.0,70.0,A
118,212719000,2024-01-01 00:00:02,34.52975,-120.94588,10.4,327.2,322.0,TROODOS SUN,IMO9698238,5BKB4,70.0,0.0,228.0,35.0,12.5,70.0,A
121,367050160,2024-01-01 00:00:03,46.75197,-92.13539,0.0,319.8,137.0,BURNS HARBOR,IMO7514713,WDC6027,70.0,0.0,330.0,34.0,8.3,70.0,A
128,538007479,2024-01-01 00:00:06,37.68875,-122.69553,6.0,356.0,7.0,HYUNDAI COURAGE,IMO9347542,V7PP4,70.0,0.0,340.0,46.0,12.5,70.0,A
133,477133500,2024-01-01 00:00:02,38.07199,-124.04890,13.1,328.2,327.0,BELLE PLAINE,IMO9638434,VRNA5,70.0,0.0,180.0,30.0,6.6,70.0,A

In [ ]:
# Select only relevant columns
df_cargo_selected =

In [ ]:
# # plot coverage area
# plot_coverage_area()

In [ ]:
relevant_columns = ["MMSI", "IMO", "BaseDateTime", "LAT", "LON", "SOG", "Heading"]
df_cargo = df_cargo[relevant_columns].reset_index(drop=True)

In [ ]:
# laat gefilterde cargo data

df_cargo = pd.read_parquet("../../data/processed/cargo_vessels.parquet")
relevant_columns = ["MMSI", "IMO", "BaseDateTime", "LAT", "LON", "SOG", "Heading"]
df_cargo = df_cargo[relevant_columns].reset_index(drop=True)

# converteer snelheden van 'SOG' van knopen naar km/u (1 knots is 1.852 km/u)

df_cargo["SOG_kph"] = df_cargo["SOG"] * 1.852

df_cargo.head(5)