### __Import packages__

In [1]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
from scripts.PHMM.viterbi_algorithm.states import *
from scripts.PHMM.viterbi_algorithm.viterbi import *
from scripts.PHMM.distributions.AIS_RF_distribution import *
import pandas as pd

### __Get testing data__

In [3]:
test_set = pd.read_pickle("../data/processed/test_data/test_set.pkl")

### __Initialize states and model__

In [4]:
begin = BeginState()
AIS = AISState()
RF = RFState()
M = MState()
end = EndState()

states = [begin, AIS, RF, M, end]
model = PHMM(states, end)

### __Make test sequence (track 1039)__

In [5]:
sequence = test_set[test_set['TrackID'] == 1039]

AIS_sequence = [(time, coord) for time, coord in zip(sequence["AIS_Timestamp"], sequence["AIS"]) 
                if pd.notna(time) and coord is not None]

RF_sequence = [(time, coord) for time, coord in zip(sequence["RF_Timestamp"], sequence["RF"]) 
               if pd.notna(time) and coord is not None]

### __Run Viterbi model of first sequence__

In [6]:
path, probability = model.viterbi(AIS_sequence, RF_sequence)

In [7]:
RF_M_indexes_pred_path = [(i, state) for i, state in enumerate(path) if state in {"RF", "M"}]
RF_M_indexes_real_path = [(i, state) for i, state in enumerate(sequence["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path}")

The indexes of RF and/or M of predicted path are: [(30, 'RF'), (126, 'RF'), (195, 'RF'), (308, 'RF')],
The indexes of RF and/or M of the real path are: [(30, 'RF'), (126, 'RF'), (195, 'RF'), (308, 'M')]

### __Make test sequence two (track 76)__

In [8]:
sequence2 = test_set[test_set['TrackID'] == 76]

AIS_sequence2 = [(time, coord) for time, coord in zip(sequence2["AIS_Timestamp"], sequence2["AIS"]) 
                if pd.notna(time) and coord is not None]

RF_sequence2 = [(time, coord) for time, coord in zip(sequence2["RF_Timestamp"], sequence2["RF"]) 
               if pd.notna(time) and coord is not None]

In [9]:
path2, probability2 = model.viterbi(AIS_sequence2, RF_sequence2)

In [10]:
RF_M_indexes_pred_path2 = [(i, state) for i, state in enumerate(path2) if state in {"RF", "M"}]
RF_M_indexes_real_path2 = [(i, state) for i, state in enumerate(sequence2["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path2}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path2}")

The indexes of RF and/or M of predicted path are: [(5, 'RF'), (150, 'RF')],
The indexes of RF and/or M of the real path are: [(5, 'RF'), (150, 'RF')]

### __Make test sequence three (track 567)__

In [11]:
sequence3 = test_set[test_set['TrackID'] == 567]

AIS_sequence3 = [(time, coord) for time, coord in zip(sequence3["AIS_Timestamp"], sequence3["AIS"]) 
                if pd.notna(time) and coord is not None]

RF_sequence3 = [(time, coord) for time, coord in zip(sequence3["RF_Timestamp"], sequence3["RF"]) 
               if pd.notna(time) and coord is not None]

In [12]:
path3, probability3 = model.viterbi(AIS_sequence3, RF_sequence3)

In [13]:
RF_M_indexes_pred_path3 = [(i, state) for i, state in enumerate(path3) if state in {"RF", "M"}]
RF_M_indexes_real_path3 = [(i, state) for i, state in enumerate(sequence3["State"]) if state in {"RF", "M"}]
print(f"The indexes of RF and/or M of predicted path are: {RF_M_indexes_pred_path3}, \
      \nThe indexes of RF and/or M of the real path are: {RF_M_indexes_real_path3}")

The indexes of RF and/or M of predicted path are: [(54, 'RF'), (394, 'RF'), (489, 'RF')],
The indexes of RF and/or M of the real path are: [(54, 'RF'), (394, 'M'), (488, 'M')]

### __Run viterbi algorithm per RF observation__

In [14]:
from haversine import haversine, Unit
import math

In [48]:
RF_data = test_set[test_set["RF"].notna()].copy()
RF_data["RF_data_point_id"] = RF_data.groupby("TrackID").cumcount() + 1

M_data = test_set[test_set["State"] == "M"].copy()
M_data["distance_km"] = M_data.apply(lambda row: haversine(row["AIS"], row["RF"], unit=Unit.KILOMETERS), axis=1)
radius_km = math.ceil(M_data["distance_km"].max())

viterbi_results = []

for _, RF_data_point in RF_data.iterrows():
    RF_coord = RF_data_point["RF"]
    RF_time = RF_data_point["RF_Timestamp"]
    
    for AIS_id, AIS_data in test_set.groupby("TrackID"):
        AIS_coords = [coord for coord in AIS_data["AIS"] if coord is not None]
        RF_within_radius = any(haversine(RF_coord, coord) <= radius_km for coord in AIS_coords)
        
        marge = pd.Timedelta(minutes=5)
        min_AIS_time = AIS_data["AIS_Timestamp"].min() - marge
        max_AIS_time = AIS_data["AIS_Timestamp"].max() + marge
        RF_within_time = min_AIS_time <= RF_time <= max_AIS_time
        
        if RF_within_radius and RF_within_time:
            AIS_seq = [(time, coord) 
                       for time, coord in zip(AIS_data["AIS_Timestamp"], AIS_data["AIS"]) 
                       if pd.notna(time) and coord is not None]
            RF_seq = [(RF_time, RF_coord)]
            
            path, prob = model.viterbi(AIS_seq, RF_seq)
            
            viterbi_results.append(
                {
                    "RF_sequence_id": RF_data_point["TrackID"],
                    "RF_data_point_id": RF_data_point["RF_data_point_id"],
                    "AIS_sequence_id": AIS_id,
                    "num_of_AIS_points": len(AIS_seq),
                    "viterbi_prob": prob,
                    "match": RF_data_point["TrackID"] == AIS_id,
                    "predicted_path": path
                })

In [90]:
def compute_penality(AIS_df, viterbi_score, weight):
    """
    Adjusts the Viterbi score based on the average log-speed of an AIS track
    In some AIS sequences, vessels may remain stationary for extended periods,
    resulting in minimal movement between positions but disproportionately high transition probabilities
    
    Args:
        sequence (pd.DataFrame): AIS data
        viterbi_score (float): The orginal log-probability score of the Viterbi algorithm
        weight (int): weight of the penalty, defaults to 1
    """
    log_speeds = []
    normal_speed = []
    time_coords = list(zip(AIS_df["AIS_Timestamp"], AIS_df["AIS"]))
    
    for i in range(1, len(time_coords)):
        prev_time, prev_coord = time_coords[i - 1]
        curr_time, curr_coord = time_coords[i]
        
        time_diff = (curr_time - prev_time).total_seconds()
        distance_diff = haversine(prev_coord, curr_coord, unit=Unit.KILOMETERS)
        speed = (distance_diff / time_diff) * 3600 if time_diff > 0 else 0.0
        
        log_speeds.append(np.log(speed + 1e-3))
        normal_speed.append(speed)
        
    mean_log_speed = np.mean(log_speeds) if log_speeds else 0
    mean_speed = np.mean(normal_speed) 
    adjusted_viterbi_score = viterbi_score + weight * mean_log_speed
    
    return mean_speed, adjusted_viterbi_score

In [91]:
for id, row in enumerate(viterbi_results):
    AIS_sequence_id = row["AIS_sequence_id"]
    
    AIS_sequence = test_set[
        (test_set["TrackID"] == AIS_sequence_id) &
        (test_set["AIS_Timestamp"].notna()) &
        (test_set["AIS"].notna())
    ]
    mean_speed, adjusted_viterbi_prob = compute_penality(AIS_sequence, row["viterbi_prob"], 3)
    viterbi_results[id]["adjusted_viterbi_prob"] = adjusted_viterbi_prob
    viterbi_results[id]["mean_speed"] = mean_speed
    viterbi_results[id]["normalized_viterbi_prob"] = adjusted_viterbi_prob/row["num_of_AIS_points"]

In [92]:
df_viterbi_results = pd.DataFrame(viterbi_results)
df_viterbi_results.head(5)

,RF_sequence_id,RF_data_point_id,AIS_sequence_id,num_of_AIS_points,viterbi_prob,match,predicted_path,adjusted_viterbi_prob,normalized_viterbi_prob,mean_speed
0,23,1,23,669,-52.385595,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-46.629094,-0.069700,17.026579
1,23,2,23,669,-56.779936,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-51.023434,-0.076268,17.026579
2,23,3,23,669,-74.742474,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-68.985973,-0.103118,17.026579
3,29,1,29,308,-35.320747,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-41.508415,-0.134768,87.213526
4,29,1,1062,386,-33.600977,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-39.846815,-0.103230,1.432557

In [71]:
df_viterbi_results[df_viterbi_results["RF_sequence_id"] == 567]

,RF_sequence_id,RF_data_point_id,AIS_sequence_id,num_of_AIS_points,viterbi_prob,match,predicted_path,adjusted_viterbi_prob,normalized_viterbi_prob,mean_speed
308,567,1,316,1118,-72.081512,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-75.664761,-0.067679,4.495181
309,567,1,567,908,-69.793220,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-62.777859,-0.069139,15.890228
310,567,2,316,1118,-76.028139,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-79.611389,-0.071209,4.495181
311,567,2,567,908,-90.034633,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-83.019272,-0.091431,15.890228
312,567,3,567,908,-78.195605,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-71.180245,-0.078392,15.890228

In [72]:
df_viterbi_results[df_viterbi_results["RF_sequence_id"] == 316]

,RF_sequence_id,RF_data_point_id,AIS_sequence_id,num_of_AIS_points,viterbi_prob,match,predicted_path,adjusted_viterbi_prob,normalized_viterbi_prob,mean_speed
170,316,1,316,1118,-92.580753,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-96.164002,-0.086014,4.495181
171,316,1,567,908,-57.557100,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-50.541739,-0.055663,15.890228
172,316,2,316,1118,-107.696384,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-111.279633,-0.099535,4.495181
173,316,2,567,908,-69.427702,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-62.412342,-0.068736,15.890228
174,316,3,316,1118,-109.200609,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-112.783859,-0.100880,4.495181
175,316,3,567,908,-57.593065,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-50.577704,-0.055702,15.890228
176,316,4,316,1118,-109.765932,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-113.349182,-0.101386,4.495181
177,316,4,567,908,-53.636039,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-46.620678,-0.051344,15.890228

In [73]:
ids = df_viterbi_results.groupby(["RF_sequence_id", "RF_data_point_id"])["adjusted_viterbi_prob"].idxmax()
best_matches = df_viterbi_results.loc[ids].reset_index(drop=True)
best_matches

,RF_sequence_id,RF_data_point_id,AIS_sequence_id,num_of_AIS_points,viterbi_prob,match,predicted_path,adjusted_viterbi_prob,normalized_viterbi_prob,mean_speed
0,23,1,23,669,-52.385595,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-46.629094,-0.069700,17.026579
1,23,2,23,669,-56.779936,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-51.023434,-0.076268,17.026579
2,23,3,23,669,-74.742474,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-68.985973,-0.103118,17.026579
3,29,1,1062,386,-33.600977,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-39.846815,-0.103230,1.432557
4,29,2,29,308,-30.637422,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-36.825090,-0.119562,87.213526
...,...,...,...,...,...,...,...,...,...,...
695,1351,1,1351,463,-41.324335,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-44.468026,-0.096043,4.518623
696,1351,2,1351,463,-44.822784,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-47.966474,-0.103599,4.518623
697,1354,1,1354,605,-53.898922,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-56.706064,-0.093729,7.631973
698,1354,2,1354,605,-54.182703,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-56.989845,-0.094198,7.631973
699,1354,3,1354,605,-56.691791,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-59.498933,-0.098345,7.631973

In [85]:
best_matches["mean_speed"].idxmax()

344

In [86]:
best_matches.iloc[344]

RF_sequence_id                                                           673
RF_data_point_id                                                           1
AIS_sequence_id                                                          673
num_of_AIS_points                                                        876
viterbi_prob                                                      -84.014034
match                                                                   True
predicted_path             [begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...
adjusted_viterbi_prob                                             -74.372492
normalized_viterbi_prob                                              -0.0849
mean_speed                                                       1852.956341
Name: 344, dtype: object

In [83]:
best_matches["mean_speed"].min()

np.float64(0.005084386063617209)

In [75]:
len(best_matches[best_matches["match"] == False])

48

In [41]:
ids = df_viterbi_results.groupby(["RF_sequence_id", "RF_data_point_id"])["viterbi_prob"].idxmax()
best_matches2 = df_viterbi_results.loc[ids].reset_index(drop=True)
best_matches2

,RF_sequence_id,RF_data_point_id,AIS_sequence_id,viterbi_prob,match,predicted_path,adjusted_viterbi_prob
0,23,1,23,-52.385595,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-48.547928
1,23,2,23,-56.779936,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-52.942268
2,23,3,23,-74.742474,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-70.904807
3,29,1,1062,-33.600977,False,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-37.764869
4,29,2,29,-30.637422,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-34.762534
...,...,...,...,...,...,...,...
695,1351,1,1351,-41.324335,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-43.420129
696,1351,2,1351,-44.822784,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-46.918577
697,1354,1,1354,-53.898922,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-55.770350
698,1354,2,1354,-54.182703,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-56.054131
699,1354,3,1354,-56.691791,True,"[begin, AIS, AIS, AIS, AIS, AIS, AIS, AIS, AIS...",-58.563219

In [25]:
test_set[test_set["TrackID"] == 316].iloc[85:90]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
34107,316,316009457,2,2024-01-03 01:40:11,2024-01-03 01:40:11,NaT,"(42.97816, -82.41604)",None,AIS
34108,316,316009457,2,2024-01-03 01:41:21,2024-01-03 01:41:21,2024-01-03 01:41:00,"(42.97494, -82.41562)","(42.97441698379122, -82.42634931899319)",M
34109,316,316009457,2,2024-01-03 01:42:30,2024-01-03 01:42:30,NaT,"(42.97194, -82.41643)",None,AIS
34110,316,316009457,2,2024-01-03 01:43:40,2024-01-03 01:43:40,NaT,"(42.96888, -82.4174)",None,AIS
34111,316,316009457,2,2024-01-03 01:44:50,2024-01-03 01:44:50,NaT,"(42.96599, -82.41887)",None,AIS

In [26]:
test_set[test_set["TrackID"] == 567].iloc[50:55]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
60005,567,366904890,2,2024-01-03 01:30:03,2024-01-03 01:30:03,NaT,"(42.3032, -83.08831)",None,AIS
60006,567,366904890,2,2024-01-03 01:33:04,2024-01-03 01:33:04,NaT,"(42.30322, -83.08829)",None,AIS
60007,567,366904890,2,2024-01-03 01:36:04,2024-01-03 01:36:04,NaT,"(42.3032, -83.08832)",None,AIS
60008,567,366904890,2,2024-01-03 01:39:03,2024-01-03 01:39:03,NaT,"(42.30321, -83.08833)",None,AIS
60009,567,366904890,2,2024-01-03 01:41:00,NaT,2024-01-03 01:41:00,None,"(42.3115251103819, -83.08503303997854)",RF

In [44]:
time = (pd.Timestamp("2024-01-03 01:41:00") - pd.Timestamp("2024-01-03 01:40:11")).total_seconds()
dist = haversine((42.97441698379122, -82.42634931899319), (42.97816, -82.41604))
AIS_RF_probability(time, dist)

np.float64(0.9740481961609083)

In [45]:
time = (pd.Timestamp("2024-01-03 01:41:00") - pd.Timestamp("2024-01-03 01:39:03")).total_seconds()
dist = haversine((42.97441698379122, -82.42634931899319), (42.30321, -83.08833))
AIS_RF_probability(time, dist)

np.float64(0.24356335140959184)

In [109]:
test_set[(test_set["TrackID"] == 673) & (test_set["AIS_Timestamp"] == "2024-01-25 20:48:09")].iloc[76092-2: 76092+ 2]

Empty DataFrame
Columns: [TrackID, MMSI, SubTrackID, Timestamp, AIS_Timestamp, RF_Timestamp, AIS, RF, State]
Index: []

In [110]:
test_set.iloc[76092-2: 76092+ 2]

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
76090,673,373485000,0,2024-01-25 20:46:42,2024-01-25 20:46:42,NaT,"(34.43152, -121.52372)",None,AIS
76091,673,373485000,0,2024-01-25 20:47:43,2024-01-25 20:47:43,NaT,"(34.43193, -121.51973)",None,AIS
76092,673,373485000,0,2024-01-25 20:48:09,2024-01-25 20:48:09,NaT,"(33.96917, -125.32927)",None,AIS
76093,673,373485000,0,2024-01-25 20:48:52,2024-01-25 20:48:52,NaT,"(34.43242, -121.51517)",None,AIS

In [97]:
AIS_673 = test_set[(test_set["TrackID"] == 673) & (test_set["AIS_Timestamp"].notna()) &(test_set["AIS"].notna())]
time_coords = list(zip(AIS_673["AIS_Timestamp"], AIS_673["AIS"]))
time_coords[:5], len(time_coords)

([(Timestamp('2024-01-24 22:10:39'), (33.87292, -127.39537)),
  (Timestamp('2024-01-24 22:12:03'), (33.87312, -127.38792)),
  (Timestamp('2024-01-24 22:13:57'), (33.87337, -127.37782)),
  (Timestamp('2024-01-24 22:23:39'), (33.87463, -127.32618)),
  (Timestamp('2024-01-24 22:24:58'), (33.8748, -127.31917))],
 876)

In [100]:
time_coords[-1:]

[(Timestamp('2024-01-25 22:10:32'), (34.46585, -121.17982))]

In [101]:
for i in range(1, len(time_coords)):
    prev_time, prev_coord = time_coords[i - 1]
    curr_time, curr_coord = time_coords[i]
    print(f"Previous time: {prev_time}, Previous coord: {prev_coord}")
    print(f"Current time: {curr_time}, Current coord: {curr_coord}")    
    
    time_diff = (curr_time - prev_time).total_seconds()
    distance_diff = haversine(curr_coord, prev_coord, unit=Unit.KILOMETERS)
    print(f"Time difference: {time_diff} seconds, Distance difference: {distance_diff} km")
    # speed = (distance_diff / time_diff) * 3600 if time_diff > 0 else 0.0
    
    # print(f"Time difference: {time_diff} seconds, Distance difference: {distance_diff} km, Speed: {speed} km/h")

Previous time: 2024-01-24 22:10:39, Previous coord: (33.87292, -127.39537)
Current time: 2024-01-24 22:12:03, Current coord: (33.87312, -127.38792)
Time difference: 84.0 seconds, Distance difference: 0.6881618861785299 km
Previous time: 2024-01-24 22:12:03, Previous coord: (33.87312, -127.38792)
Current time: 2024-01-24 22:13:57, Current coord: (33.87337, -127.37782)
Time difference: 114.0 seconds, Distance difference: 0.9328688349654652 km
Previous time: 2024-01-24 22:13:57, Previous coord: (33.87337, -127.37782)
Current time: 2024-01-24 22:23:39, Current coord: (33.87463, -127.32618)
Time difference: 582.0 seconds, Distance difference: 4.769536142314554 km
Previous time: 2024-01-24 22:23:39, Previous coord: (33.87463, -127.32618)
Current time: 2024-01-24 22:24:58, Current coord: (33.8748, -127.31917)
Time difference: 79.0 seconds, Distance difference: 0.6474437190567326 km
Previous time: 2024-01-24 22:24:58, Previous coord: (33.8748, -127.31917)
Current time: 2024-01-24 22:28:46, Current coord: (33.8753, -127.29898)
Time difference: 228.0 seconds, Distance difference: 1.8647754527186082 km
Previous time: 2024-01-24 22:28:46, Previous coord: (33.8753, -127.29898)
Current time: 2024-01-24 22:29:52, Current coord: (33.87542, -127.29312)
Time difference: 66.0 seconds, Distance difference: 0.5411594080152919 km
Previous time: 2024-01-24 22:29:52, Previous coord: (33.87542, -127.29312)
Current time: 2024-01-24 22:30:58, Current coord: (33.87553, -127.28713)
Time difference: 66.0 seconds, Distance difference: 0.5531309804360252 km
Previous time: 2024-01-24 22:30:58, Previous coord: (33.87553, -127.28713)
Current time: 2024-01-24 22:32:27, Current coord: (33.87567, -127.27925)
Time difference: 89.0 seconds, Distance difference: 0.7276456647149938 km
Previous time: 2024-01-24 22:32:27, Previous coord: (33.87567, -127.27925)
Current time: 2024-01-24 22:34:15, Current coord: (33.8759, -127.26962)
Time difference: 108.0 seconds, Distance difference: 0.8894044231176125 km
Previous time: 2024-01-24 22:34:15, Previous coord: (33.8759, -127.26962)
Current time: 2024-01-24 22:35:21, Current coord: (33.876, -127.26367)
Time difference: 66.0 seconds, Distance difference: 0.5494124107387167 km
Previous time: 2024-01-24 22:35:21, Previous coord: (33.876, -127.26367)
Current time: 2024-01-24 22:36:33, Current coord: (33.87608, -127.2573)
Time difference: 72.0 seconds, Distance difference: 0.5881406412740374 km
Previous time: 2024-01-24 22:36:33, Previous coord: (33.87608, -127.2573)
Current time: 2024-01-24 22:37:39, Current coord: (33.8762, -127.25147)
Time difference: 66.0 seconds, Distance difference: 0.5383857384211698 km
Previous time: 2024-01-24 22:37:39, Previous coord: (33.8762, -127.25147)
Current time: 2024-01-24 22:38:45, Current coord: (33.87633, -127.2456)
Time difference: 66.0 seconds, Distance difference: 0.542105093162095 km
Previous time: 2024-01-24 22:38:45, Previous coord: (33.87633, -127.2456)
Current time: 2024-01-24 22:39:46, Current coord: (33.87642, -127.24032)
Time difference: 61.0 seconds, Distance difference: 0.4875462330703153 km
Previous time: 2024-01-24 22:39:46, Previous coord: (33.87642, -127.24032)
Current time: 2024-01-24 22:40:51, Current coord: (33.87655, -127.2345)
Time difference: 65.0 seconds, Distance difference: 0.537489415702626 km
Previous time: 2024-01-24 22:40:51, Previous coord: (33.87655, -127.2345)
Current time: 2024-01-24 22:42:03, Current coord: (33.87673, -127.22827)
Time difference: 72.0 seconds, Distance difference: 0.5754927906343809 km
Previous time: 2024-01-24 22:42:03, Previous coord: (33.87673, -127.22827)
Current time: 2024-01-24 22:43:09, Current coord: (33.87688, -127.2224)
Time difference: 66.0 seconds, Distance difference: 0.5421655245040159 km
Previous time: 2024-01-24 22:43:09, Previous coord: (33.87688, -127.2224)
Current time: 2024-01-24 22:44:10, Current coord: (33.87702, -127.21713)
Time difference: 61.0 seconds, Distance difference: 0.486766039817162 km
Previous time: 2024-01-24 22:44:10, Previous coord: (33.87702, -127.21713)
Current time: 2024-01-24 22:45:27, Current coord: (33.87718, -127.2103)
Time difference: 77.0 seconds, Distance difference: 0.6307833191945008 km
Previous time: 2024-01-24 22:45:27, Previous coord: (33.87718, -127.2103)
Current time: 2024-01-24 22:47:21, Current coord: (33.87742, -127.20042)
Time difference: 114.0 seconds, Distance difference: 0.9124906495326096 km
Previous time: 2024-01-24 22:47:21, Previous coord: (33.87742, -127.20042)
Current time: 2024-01-24 22:48:27, Current coord: (33.87758, -127.19457)
Time difference: 66.0 seconds, Distance difference: 0.5403511059741181 km
Previous time: 2024-01-24 22:48:27, Previous coord: (33.87758, -127.19457)
Current time: 2024-01-24 22:49:33, Current coord: (33.87773, -127.18887)
Time difference: 66.0 seconds, Distance difference: 0.5264738108135707 km
Previous time: 2024-01-24 22:49:33, Previous coord: (33.87773, -127.18887)
Current time: 2024-01-24 22:50:39, Current coord: (33.87792, -127.18315)
Time difference: 66.0 seconds, Distance difference: 0.5284773029873986 km
Previous time: 2024-01-24 22:50:39, Previous coord: (33.87792, -127.18315)
Current time: 2024-01-24 22:52:03, Current coord: (33.87813, -127.17595)
Time difference: 84.0 seconds, Distance difference: 0.6650928924191631 km
Previous time: 2024-01-24 22:52:03, Previous coord: (33.87813, -127.17595)
Current time: 2024-01-24 22:53:22, Current coord: (33.87832, -127.16908)
Time difference: 79.0 seconds, Distance difference: 0.634568526140543 km
Previous time: 2024-01-24 22:53:22, Previous coord: (33.87832, -127.16908)
Current time: 2024-01-24 22:54:39, Current coord: (33.8785, -127.16243)
Time difference: 77.0 seconds, Distance difference: 0.6142318825803236 km
Previous time: 2024-01-24 22:54:39, Previous coord: (33.8785, -127.16243)
Current time: 2024-01-24 22:55:52, Current coord: (33.87867, -127.15603)
Time difference: 73.0 seconds, Distance difference: 0.5911276419919458 km
Previous time: 2024-01-24 22:55:52, Previous coord: (33.87867, -127.15603)
Current time: 2024-01-24 22:57:03, Current coord: (33.87882, -127.14997)
Time difference: 71.0 seconds, Distance difference: 0.5596852623348262 km
Previous time: 2024-01-24 22:57:03, Previous coord: (33.87882, -127.14997)
Current time: 2024-01-24 22:58:10, Current coord: (33.87905, -127.14417)
Time difference: 67.0 seconds, Distance difference: 0.5360436921569761 km
Previous time: 2024-01-24 22:58:10, Previous coord: (33.87905, -127.14417)
Current time: 2024-01-24 22:59:15, Current coord: (33.87928, -127.13857)
Time difference: 65.0 seconds, Distance difference: 0.5176008602230375 km
Previous time: 2024-01-24 22:59:15, Previous coord: (33.87928, -127.13857)
Current time: 2024-01-24 23:00:03, Current coord: (33.87947, -127.13445)
Time difference: 48.0 seconds, Distance difference: 0.38092660809420353 km
Previous time: 2024-01-24 23:00:03, Previous coord: (33.87947, -127.13445)
Current time: 2024-01-24 23:01:09, Current coord: (33.8797, -127.12872)
Time difference: 66.0 seconds, Distance difference: 0.52958499084282 km
Previous time: 2024-01-24 23:01:09, Previous coord: (33.8797, -127.12872)
Current time: 2024-01-24 23:02:15, Current coord: (33.87988, -127.12305)
Time difference: 66.0 seconds, Distance difference: 0.5238094512483311 km
Previous time: 2024-01-24 23:02:15, Previous coord: (33.87988, -127.12305)
Current time: 2024-01-24 23:03:21, Current coord: (33.88008, -127.11738)
Time difference: 66.0 seconds, Distance difference: 0.5238979768520904 km
Previous time: 2024-01-24 23:03:21, Previous coord: (33.88008, -127.11738)
Current time: 2024-01-24 23:04:27, Current coord: (33.88027, -127.11178)
Time difference: 66.0 seconds, Distance difference: 0.517394049921383 km
Previous time: 2024-01-24 23:04:27, Previous coord: (33.88027, -127.11178)
Current time: 2024-01-24 23:05:33, Current coord: (33.88048, -127.10603)
Time difference: 66.0 seconds, Distance difference: 0.5313218607916165 km
Previous time: 2024-01-24 23:05:33, Previous coord: (33.88048, -127.10603)
Current time: 2024-01-24 23:06:45, Current coord: (33.8807, -127.09983)
Time difference: 72.0 seconds, Distance difference: 0.5728711306850008 km
Previous time: 2024-01-24 23:06:45, Previous coord: (33.8807, -127.09983)
Current time: 2024-01-24 23:07:57, Current coord: (33.88095, -127.09367)
Time difference: 72.0 seconds, Distance difference: 0.5693335116116733 km
Previous time: 2024-01-24 23:07:57, Previous coord: (33.88095, -127.09367)
Current time: 2024-01-24 23:09:03, Current coord: (33.88117, -127.08802)
Time difference: 66.0 seconds, Distance difference: 0.522146217215554 km
Previous time: 2024-01-24 23:09:03, Previous coord: (33.88117, -127.08802)
Current time: 2024-01-24 23:15:45, Current coord: (33.88317, -127.05328)
Time difference: 402.0 seconds, Distance difference: 3.2146406859531544 km
Previous time: 2024-01-24 23:15:45, Previous coord: (33.88317, -127.05328)
Current time: 2024-01-24 23:16:52, Current coord: (33.88367, -127.04763)
Time difference: 67.0 seconds, Distance difference: 0.5245133702941893 km
Previous time: 2024-01-24 23:16:52, Previous coord: (33.88367, -127.04763)
Current time: 2024-01-24 23:17:57, Current coord: (33.88412, -127.04195)
Time difference: 65.0 seconds, Distance difference: 0.5267070524234099 km
Previous time: 2024-01-24 23:17:57, Previous coord: (33.88412, -127.04195)
Current time: 2024-01-24 23:19:03, Current coord: (33.88457, -127.03625)
Time difference: 66.0 seconds, Distance difference: 0.5285421828101595 km
Previous time: 2024-01-24 23:19:03, Previous coord: (33.88457, -127.03625)
Current time: 2024-01-24 23:20:09, Current coord: (33.88502, -127.03065)
Time difference: 66.0 seconds, Distance difference: 0.5193506420402042 km
Previous time: 2024-01-24 23:20:09, Previous coord: (33.88502, -127.03065)
Current time: 2024-01-24 23:21:15, Current coord: (33.88543, -127.02485)
Time difference: 66.0 seconds, Distance difference: 0.5373313188528807 km
Previous time: 2024-01-24 23:21:15, Previous coord: (33.88543, -127.02485)
Current time: 2024-01-24 23:22:27, Current coord: (33.8859, -127.01875)
Time difference: 72.0 seconds, Distance difference: 0.5655037484008811 km
Previous time: 2024-01-24 23:22:27, Previous coord: (33.8859, -127.01875)
Current time: 2024-01-24 23:23:33, Current coord: (33.88635, -127.01302)
Time difference: 66.0 seconds, Distance difference: 0.5312881293032311 km
Previous time: 2024-01-24 23:23:33, Previous coord: (33.88635, -127.01302)
Current time: 2024-01-24 23:24:45, Current coord: (33.88685, -127.00688)
Time difference: 72.0 seconds, Distance difference: 0.5694902017746694 km
Previous time: 2024-01-24 23:24:45, Previous coord: (33.88685, -127.00688)
Current time: 2024-01-24 23:25:52, Current coord: (33.88733, -127.00105)
Time difference: 67.0 seconds, Distance difference: 0.5407916046910908 km
Previous time: 2024-01-24 23:25:52, Previous coord: (33.88733, -127.00105)
Current time: 2024-01-24 23:26:58, Current coord: (33.8878, -126.9954)
Time difference: 66.0 seconds, Distance difference: 0.5241450573357872 km
Previous time: 2024-01-24 23:26:58, Previous coord: (33.8878, -126.9954)
Current time: 2024-01-24 23:28:51, Current coord: (33.88863, -126.9855)
Time difference: 113.0 seconds, Distance difference: 0.9184784377261384 km
Previous time: 2024-01-24 23:28:51, Previous coord: (33.88863, -126.9855)
Current time: 2024-01-24 23:29:58, Current coord: (33.8891, -126.97975)
Time difference: 67.0 seconds, Distance difference: 0.5333224765438501 km
Previous time: 2024-01-24 23:29:58, Previous coord: (33.8891, -126.97975)
Current time: 2024-01-24 23:31:03, Current coord: (33.88955, -126.97402)
Time difference: 65.0 seconds, Distance difference: 0.5312683764402362 km
Previous time: 2024-01-24 23:31:03, Previous coord: (33.88955, -126.97402)
Current time: 2024-01-24 23:32:09, Current coord: (33.88998, -126.96825)
Time difference: 66.0 seconds, Distance difference: 0.5347380975277687 km
Previous time: 2024-01-24 23:32:09, Previous coord: (33.88998, -126.96825)
Current time: 2024-01-24 23:33:16, Current coord: (33.89047, -126.96242)
Time difference: 67.0 seconds, Distance difference: 0.540882803767567 km
Previous time: 2024-01-24 23:33:16, Previous coord: (33.89047, -126.96242)
Current time: 2024-01-24 23:34:22, Current coord: (33.89095, -126.95678)
Time difference: 66.0 seconds, Distance difference: 0.5233197385918271 km
Previous time: 2024-01-24 23:34:22, Previous coord: (33.89095, -126.95678)
Current time: 2024-01-24 23:35:34, Current coord: (33.89147, -126.9505)
Time difference: 72.0 seconds, Distance difference: 0.5825382755461215 km
Previous time: 2024-01-24 23:35:34, Previous coord: (33.89147, -126.9505)
Current time: 2024-01-24 23:36:46, Current coord: (33.89202, -126.9442)
Time difference: 72.0 seconds, Distance difference: 0.5847111073921858 km
Previous time: 2024-01-24 23:36:46, Previous coord: (33.89202, -126.9442)
Current time: 2024-01-24 23:37:58, Current coord: (33.89255, -126.93792)
Time difference: 72.0 seconds, Distance difference: 0.5826424274478643 km
Previous time: 2024-01-24 23:37:58, Previous coord: (33.89255, -126.93792)
Current time: 2024-01-24 23:39:03, Current coord: (33.89302, -126.93213)
Time difference: 65.0 seconds, Distance difference: 0.5369725964861993 km
Previous time: 2024-01-24 23:39:03, Previous coord: (33.89302, -126.93213)
Current time: 2024-01-24 23:40:27, Current coord: (33.89362, -126.92487)
Time difference: 84.0 seconds, Distance difference: 0.6734147916840711 km
Previous time: 2024-01-24 23:40:27, Previous coord: (33.89362, -126.92487)
Current time: 2024-01-24 23:41:33, Current coord: (33.89408, -126.91903)
Time difference: 66.0 seconds, Distance difference: 0.5414530530710915 km
Previous time: 2024-01-24 23:41:33, Previous coord: (33.89408, -126.91903)
Current time: 2024-01-24 23:42:39, Current coord: (33.89455, -126.91338)
Time difference: 66.0 seconds, Distance difference: 0.5241039916656659 km
Previous time: 2024-01-24 23:42:39, Previous coord: (33.89455, -126.91338)
Current time: 2024-01-24 23:43:45, Current coord: (33.895, -126.90755)
Time difference: 66.0 seconds, Distance difference: 0.5404242889663627 km
Previous time: 2024-01-24 23:43:45, Previous coord: (33.895, -126.90755)
Current time: 2024-01-24 23:44:51, Current coord: (33.89543, -126.90178)
Time difference: 66.0 seconds, Distance difference: 0.5347042019436914 km
Previous time: 2024-01-24 23:44:51, Previous coord: (33.89543, -126.90178)
Current time: 2024-01-24 23:45:57, Current coord: (33.89583, -126.89605)
Time difference: 66.0 seconds, Distance difference: 0.5307346289272906 km
Previous time: 2024-01-24 23:45:57, Previous coord: (33.89583, -126.89605)
Current time: 2024-01-24 23:46:58, Current coord: (33.89622, -126.89083)
Time difference: 61.0 seconds, Distance difference: 0.4837411409839329 km
Previous time: 2024-01-24 23:46:58, Previous coord: (33.89622, -126.89083)
Current time: 2024-01-24 23:48:04, Current coord: (33.89667, -126.88508)
Time difference: 66.0 seconds, Distance difference: 0.5330621842263531 km
Previous time: 2024-01-24 23:48:04, Previous coord: (33.89667, -126.88508)
Current time: 2024-01-24 23:49:09, Current coord: (33.89708, -126.87937)
Time difference: 65.0 seconds, Distance difference: 0.5289821906287006 km
Previous time: 2024-01-24 23:49:09, Previous coord: (33.89708, -126.87937)
Current time: 2024-01-24 23:50:15, Current coord: (33.89753, -126.87372)
Time difference: 66.0 seconds, Distance difference: 0.5238687054441478 km
Previous time: 2024-01-24 23:50:15, Previous coord: (33.89753, -126.87372)
Current time: 2024-01-24 23:51:16, Current coord: (33.89797, -126.86843)
Time difference: 61.0 seconds, Distance difference: 0.4906895974120939 km
Previous time: 2024-01-24 23:51:16, Previous coord: (33.89797, -126.86843)
Current time: 2024-01-24 23:52:27, Current coord: (33.89845, -126.8622)
Time difference: 71.0 seconds, Distance difference: 0.5774710813930919 km
Previous time: 2024-01-24 23:52:27, Previous coord: (33.89845, -126.8622)
Current time: 2024-01-24 23:53:33, Current coord: (33.89887, -126.85642)
Time difference: 66.0 seconds, Distance difference: 0.5355039096876942 km
Previous time: 2024-01-24 23:53:33, Previous coord: (33.89887, -126.85642)
Current time: 2024-01-24 23:54:39, Current coord: (33.89918, -126.85075)
Time difference: 66.0 seconds, Distance difference: 0.5244429564948847 km
Previous time: 2024-01-24 23:54:39, Previous coord: (33.89918, -126.85075)
Current time: 2024-01-24 23:55:45, Current coord: (33.89955, -126.84495)
Time difference: 66.0 seconds, Distance difference: 0.5368837393293872 km
Previous time: 2024-01-24 23:55:45, Previous coord: (33.89955, -126.84495)
Current time: 2024-01-24 23:56:51, Current coord: (33.89988, -126.83913)
Time difference: 66.0 seconds, Distance difference: 0.5384005975871597 km
Previous time: 2024-01-24 23:56:51, Previous coord: (33.89988, -126.83913)
Current time: 2024-01-24 23:57:58, Current coord: (33.90022, -126.83327)
Time difference: 67.0 seconds, Distance difference: 0.5421581002826551 km
Previous time: 2024-01-24 23:57:58, Previous coord: (33.90022, -126.83327)
Current time: 2024-01-25 00:00:09, Current coord: (33.90098, -126.82178)
Time difference: 131.0 seconds, Distance difference: 1.0638043211095405 km
Previous time: 2024-01-25 00:00:09, Previous coord: (33.90098, -126.82178)
Current time: 2024-01-25 00:01:10, Current coord: (33.90133, -126.81633)
Time difference: 61.0 seconds, Distance difference: 0.5044949538854505 km
Previous time: 2024-01-25 00:01:10, Previous coord: (33.90133, -126.81633)
Current time: 2024-01-25 00:02:51, Current coord: (33.90193, -126.80755)
Time difference: 101.0 seconds, Distance difference: 0.813061439908718 km
Previous time: 2024-01-25 00:02:51, Previous coord: (33.90193, -126.80755)
Current time: 2024-01-25 00:03:57, Current coord: (33.90235, -126.80167)
Time difference: 66.0 seconds, Distance difference: 0.5446767442672014 km
Previous time: 2024-01-25 00:03:57, Previous coord: (33.90235, -126.80167)
Current time: 2024-01-25 00:05:10, Current coord: (33.90277, -126.79535)
Time difference: 73.0 seconds, Distance difference: 0.5851427185069614 km
Previous time: 2024-01-25 00:05:10, Previous coord: (33.90277, -126.79535)
Current time: 2024-01-25 00:06:57, Current coord: (33.9033, -126.78587)
Time difference: 107.0 seconds, Distance difference: 0.8768917882592518 km
Previous time: 2024-01-25 00:06:57, Previous coord: (33.9033, -126.78587)
Current time: 2024-01-25 00:08:03, Current coord: (33.9036, -126.7802)
Time difference: 66.0 seconds, Distance difference: 0.5243439406197222 km
Previous time: 2024-01-25 00:08:03, Previous coord: (33.9036, -126.7802)
Current time: 2024-01-25 00:09:09, Current coord: (33.90397, -126.77433)
Time difference: 66.0 seconds, Distance difference: 0.5432975408573071 km
Previous time: 2024-01-25 00:09:09, Previous coord: (33.90397, -126.77433)
Current time: 2024-01-25 00:10:21, Current coord: (33.9044, -126.76813)
Time difference: 72.0 seconds, Distance difference: 0.5741845233858601 km
Previous time: 2024-01-25 00:10:21, Previous coord: (33.9044, -126.76813)
Current time: 2024-01-25 00:11:27, Current coord: (33.90483, -126.76225)
Time difference: 66.0 seconds, Distance difference: 0.5447575190128774 km
Previous time: 2024-01-25 00:11:27, Previous coord: (33.90483, -126.76225)
Current time: 2024-01-25 00:12:34, Current coord: (33.9052, -126.75647)
Time difference: 67.0 seconds, Distance difference: 0.5350080602980002 km
Previous time: 2024-01-25 00:12:34, Previous coord: (33.9052, -126.75647)
Current time: 2024-01-25 00:13:39, Current coord: (33.9055, -126.75067)
Time difference: 65.0 seconds, Distance difference: 0.5363059138799801 km
Previous time: 2024-01-25 00:13:39, Previous coord: (33.9055, -126.75067)
Current time: 2024-01-25 00:14:45, Current coord: (33.90585, -126.74487)
Time difference: 66.0 seconds, Distance difference: 0.5366783859106813 km
Previous time: 2024-01-25 00:14:45, Previous coord: (33.90585, -126.74487)

In [98]:
AIS_673

,TrackID,MMSI,SubTrackID,Timestamp,AIS_Timestamp,RF_Timestamp,AIS,RF,State
75297,673,373485000,0,2024-01-24 22:10:39,2024-01-24 22:10:39,NaT,"(33.87292, -127.39537)",None,AIS
75298,673,373485000,0,2024-01-24 22:12:03,2024-01-24 22:12:03,NaT,"(33.87312, -127.38792)",None,AIS
75299,673,373485000,0,2024-01-24 22:13:57,2024-01-24 22:13:57,NaT,"(33.87337, -127.37782)",None,AIS
75300,673,373485000,0,2024-01-24 22:23:39,2024-01-24 22:23:39,NaT,"(33.87463, -127.32618)",None,AIS
75301,673,373485000,0,2024-01-24 22:24:58,2024-01-24 22:24:58,NaT,"(33.8748, -127.31917)",None,AIS
...,...,...,...,...,...,...,...,...,...
76168,673,373485000,0,2024-01-25 22:06:01,2024-01-25 22:06:01,NaT,"(34.4652, -121.20328)",None,AIS
76169,673,373485000,0,2024-01-25 22:07:12,2024-01-25 22:07:12,NaT,"(34.46543, -121.19402)",None,AIS
76170,673,373485000,0,2024-01-25 22:08:13,2024-01-25 22:08:13,NaT,"(34.46557, -121.18977)",None,AIS
76171,673,373485000,0,2024-01-25 22:09:21,2024-01-25 22:09:21,NaT,"(34.46568, -121.18482)",None,AIS
76172,673,373485000,0,2024-01-25 22:10:32,2024-01-25 22:10:32,NaT,"(34.46585, -121.17982)",None,AIS

In [ ]:
time_coords = list(zip(AIS_df["AIS_Timestamp"], AIS_df["AIS"]))
    
    for i in range(1, len(time_coords)):
        prev_time, prev_coord = time_coords[i - 1]
        curr_time, curr_coord = time_coords[i]
        
        time_diff = (curr_time - prev_time).total_seconds()
        distance_diff = haversine(prev_coord, curr_coord, unit=Unit.KILOMETERS)
        speed = (distance_diff / time_diff) * 3600 if time_diff > 0 else 0.0
        
        log_speeds.append(np.log(speed + 1e-3))
        normal_speed.append(speed)